### ISSUE TITLE
请问动态域名服务怎么绑定到分配的其他IPV6的主机上?

### ISSUE THREAD

**Issue by hy817120** [gdy666/lucky#11]
![屏幕截图 2022-09-21 222028](https://user-images.githubusercontent.com/46050478/191530202-fdd6a526-eb40-4c06-91f6-b07044b7c4a3.png)
![QQ图片20220921222205](https://user-images.githubusercontent.com/46050478/191530359-dbd0dbca-d5ce-4342-b31e-7b37cce55a1c.png)
我使用动态域名服务,只能获取到lan口的公网ipv6,
但是家庭网络中, 我群晖和其他设备都分配到ipv6, 这种情况下怎么绑定到其他ipv6设备上呢?
以前用爱快,可以直接绑定其他设备上, 直接绑定到mac地址或者DUID上, 请问此脚本如何实现,绑定到其他设备上?

**Comment by gdy666** [comment]
目前只能在群晖或者其他设备上面运行lucky才可以获取到其他ipv6设备的IP.

**Comment by hy817120** [comment]
> 现在只能在群晖或者其他设备运行，幸运的才可以获取到其他ipv6设备的IP。

感谢回复

**Comment by shobalpeng** [comment]
> 目前只能在群晖或者其他设备上面运行lucky才可以获取到其他ipv6设备的IP.

在群晖里用docker安装了，没找到哪里能获取其他设备ipv6的地方，只有接口获取或者网卡获取，请问下怎样才能通过mac地址获其他设备的ipv6呀

**Comment by gdy666** [comment]
> > 目前只能在群晖或者其他设备上面运行lucky才可以获取到其他ipv6设备的IP.
> 
> 在群晖里用docker安装了，没找到哪里能获取其他设备ipv6的地方，只有接口获取或者网卡获取，请问下怎样才能通过mac地址获其他设备的ipv6呀

可能表达得不够清除,意思是目前的情况是,哪个设备运行lucky,lucky就只能获取哪个设备的ipv6地址.
其实要同步局域网内其它设备的ipv6也不难,你只要确定每次ipv6地址变化后,局域网内的设备的ipv6地址只有后边固定部分改变的话麻烦联系一下我.因为我这边的网络没有IPv6前缀,这也是我一直没法实现这功能的原因.

**Comment by shobalpeng** [comment]
> > > 目前只能在群晖或者其他设备上面运行lucky才可以获取到其他ipv6设备的IP.
> > 
> > 
> > 在群晖里用docker安装了，没找到哪里能获取其他设备ipv6的地方，只有接口获取或者网卡获取，请问下怎样才能通过mac地址获其他设备的ipv6呀
> 
> 可能表达得不够清除,意思是目前的情况是,哪个设备运行lucky,lucky就只能获取哪个设备的ipv6地址. 其实要同步局域网内其它设备的ipv6也不难,你只要确定每次ipv6地址变化后,局域网内的设备的ipv6地址只有后边固定部分改变的话麻烦联系一下我.因为我这边的网络没有IPv6前缀,这也是我一直没法实现这功能的原因.

去找了一下我路由器上的log，好像变动蛮大的，
不过老毛子的固件上的ddns可以根据mac地址获取ipv6，不知道是不是可以参考
Oct 15 01:33:23 【DNSPod动态域名】: 目前 IP: 240e:3b7:3223:b360:b8c8:20a9:4feb:4755
Oct 15 01:33:23 【DNSPod动态域名】: 上次 IP: 240e:3b7:3225:52b0:b8c8:20a9:4feb:4755
Oct 15 01:33:37 【DNSPod动态域名】: 目前 IP: 240e:3b7:3223:b360:20c:29ff:fe98:8f3f
Oct 15 01:33:37 【DNSPod动态域名】: 上次 IP: 240e:3b7:3225:52b0:20c:29ff:fe98:8f3f
Oct 19 00:18:15 【DNSPod动态域名】: 目前 IP: 240e:3b7:3223:b360:b8c8:20a9:4feb:4755
Oct 19 00:18:15 【DNSPod动态域名】: 上次 IP: 240e:3b7:3223:b360:e869:7156:665f:d7d1

**Comment by shobalpeng** [comment]
这个是老毛子ddns下的脚本，可以参考参考


# 自行测试哪个代码能获取正确的IP，删除前面的#可生效
arIpAddress () {
# IPv4地址获取
# 获得外网地址
curltest=`which curl`
if [ -z "$curltest" ] || [ ! -s "`which curl`" ] ; then
    #wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "https://www.cloudflare.com/cdn-cgi/trace" | awk -F= '/ip/{print $2}'
    #wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "http://myip.ipip.net" | grep "当前 IP" | grep -E -o '([0-9]+\.){3}[0-9]+' | head -n1 | cut -d' ' -f1
    wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "http://members.3322.org/dyndns/getip" | grep -E -o '([0-9]+\.){3}[0-9]+' | head -n1 | cut -d' ' -f1
    #wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "ip.3322.net" | grep -E -o '([0-9]+\.){3}[0-9]+' | head -n1 | cut -d' ' -f1
    #wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "http://ddns.oray.com/checkip" | grep -E -o '([0-9]+\.){3}[0-9]+' | head -n1 | cut -d' ' -f1
else
    #curl -L --user-agent "$user_agent" -s "https://www.cloudflare.com/cdn-cgi/trace" | awk -F= '/ip/{print $2}'
    #curl -L --user-agent "$user_agent" -s "http://myip.ipip.net" | grep "当前 IP" | grep -E -o '([0-9]+\.){3}[0-9]+' | head -n1 | cut -d' ' -f1
    curl -L --user-agent "$user_agent" -s "http://members.3322.org/dyndns/getip" | grep -E -o '([0-9]+\.){3}[0-9]+' | head -n1 | cut -d' ' -f1
    #curl -L --user-agent "$user_agent" -s ip.3322.net | grep -E -o '([0-9]+\.){3}[0-9]+' | head -n1 | cut -d' ' -f1
    #curl -L --user-agent "$user_agent" -s http://ddns.oray.com/checkip | grep -E -o '([0-9]+\.){3}[0-9]+' | head -n1 | cut -d' ' -f1
fi
}
arIpAddress6 () {
# IPv6地址获取
# 因为一般ipv6没有nat ipv6的获得可以本机获得
ifconfig $(nvram get wan0_ifname_t) | awk '/Global/{print $3}' | awk -F/ '{print $1}'
#curl -6 -s https://www.cloudflare.com/cdn-cgi/trace | awk -F= '/ip/{print $2}'
}
if [ "$IPv6_neighbor" != "1" ] ; then
if [ "$IPv6" = "1" ] ; then
arIpAddress=$(arIpAddress6)
else
arIpAddress=$(arIpAddress)
fi
else
arIpAddress=$inet6_neighbor
inet6_neighbor=""
IPv6_neighbor=0
fi

# 根据 ip -f inet6 neighbor show 获取终端的信息，设置 ddns 解析，实现每个终端的 IPV6 动态域名
# 参数说明：使用 @ 符号分割，①前缀名称 ②域名 ③MAC【不限大小写】
# ④匹配关键词的ip6地址【可留空】 ⑤排除关键词的ip6地址【可留空】 ⑥手动指定ip【可留空】 
# 下面是信号填写例子：（删除前面的#可生效）
cat >/tmp/ip6_ddns.inf <<-\EOF
#www@google.com@09:9B:9A:90:9F:D9@@fe80::@  # 参数填写例子

	



EOF
cat /tmp/ip6_ddns.inf | grep -v '^#'  | grep -v "^$" > /tmp/ip6_ddns_inf
rm -f /tmp/ip6_ddns.inf

**Comment by gdy666** [comment]
> 这个是老毛子ddns下的脚本，可以参考参考
> 
> # 自行测试哪个代码能获取正确的IP，删除前面的#可生效
> arIpAddress () {
> 
> # IPv4地址获取
> # 获得外网地址
> curltest=`which curl` if [ -z "$curltest" ] || [ ! -s "`which curl`" ] ; then #wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "https://www.cloudflare.com/cdn-cgi/trace" | awk -F= '/ip/{print $2}' #wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "http://myip.ipip.net" | grep "当前 IP" | grep -E -o '([0-9]+.){3}[0-9]+' | head -n1 | cut -d' ' -f1 wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "http://members.3322.org/dyndns/getip" | grep -E -o '([0-9]+.){3}[0-9]+' | head -n1 | cut -d' ' -f1 #wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "ip.3322.net" | grep -E -o '([0-9]+.){3}[0-9]+' | head -n1 | cut -d' ' -f1 #wget -T 5 -t 3 --user-agent "$user_agent" --quiet --output-document=- "http://ddns.oray.com/checkip" | grep -E -o '([0-9]+.){3}[0-9]+' | head -n1 | cut -d' ' -f1 else #curl -L --user-agent "$user_agent" -s "https://www.cloudflare.com/cdn-cgi/trace" | awk -F= '/ip/{print $2}' #curl -L --user-agent "$user_agent" -s "http://myip.ipip.net" | grep "当前 IP" | grep -E -o '([0-9]+.){3}[0-9]+' | head -n1 | cut -d' ' -f1 curl -L --user-agent "$user_agent" -s "http://members.3322.org/dyndns/getip" | grep -E -o '([0-9]+.){3}[0-9]+' | head -n1 | cut -d' ' -f1 #curl -L --user-agent "$user_agent" -s ip.3322.net | grep -E -o '([0-9]+.){3}[0-9]+' | head -n1 | cut -d' ' -f1 #curl -L --user-agent "$user_agent" -s http://ddns.oray.com/checkip | grep -E -o '([0-9]+.){3}[0-9]+' | head -n1 | cut -d' ' -f1 fi } arIpAddress6 () {
> 
> # IPv6地址获取
> # 因为一般ipv6没有nat ipv6的获得可以本机获得
> ifconfig $(nvram get wan0_ifname_t) | awk '/Global/{print $3}' | awk -F/ '{print $1}' #curl -6 -s https://www.cloudflare.com/cdn-cgi/trace | awk -F= '/ip/{print $2}' } if [ "$IPv6_neighbor" != "1" ] ; then if [ "$IPv6" = "1" ] ; then arIpAddress=$(arIpAddress6) else arIpAddress=$(arIpAddress) fi else arIpAddress=$inet6_neighbor inet6_neighbor="" IPv6_neighbor=0 fi
> 
> # 根据 ip -f inet6 neighbor show 获取终端的信息，设置 ddns 解析，实现每个终端的 IPV6 动态域名
> # 参数说明：使用 @ 符号分割，①前缀名称 ②域名 ③MAC【不限大小写】
> # ④匹配关键词的ip6地址【可留空】 ⑤排除关键词的ip6地址【可留空】 ⑥手动指定ip【可留空】
> # 下面是信号填写例子：（删除前面的#可生效）
> cat >/tmp/ip6_ddns.inf <<-\EOF #www@google.com@09:9B:9A:90:9F:D9@@fe80::@ # 参数填写例子
> 
> EOF cat /tmp/ip6_ddns.inf | grep -v '^#' | grep -v "^$" > /tmp/ip6_ddns_inf rm -f /tmp/ip6_ddns.inf

上面的代码貌似只有
ip -f inet6 neighbor show
有一点参考价值,不过目前我这边的网络环境没有ipv6前缀,很难作进一步的其它测试验证...

**Comment by gdy666** [comment]
> > 目前只能在群晖或者其他设备上面运行lucky才可以获取到其他ipv6设备的IP.
> 
> 在群晖里用docker安装了，没找到哪里能获取其他设备ipv6的地方，只有接口获取或者网卡获取，请问下怎样才能通过mac地址获其他设备的ipv6呀

后续我会根据这篇文章https://microcai.org/2020/04/27/all-device-ipv6ed-and-ddnsed.html 
实现试试.

**Comment by hy817120** [comment]
> > > 现在只能在群晖或者其他设备运行，幸运的才可以获取到其他ipv6设备的IP。
> > 
> > 
> > 在群晖里用docker能力安装了，没找到能获取ipv6的地方，只有mac接口或者网卡获取其他设备的地址，请问下怎么获取其他设备的ipv6呀
> 
> 和我所有的微博会根据文章[orghttps:](https://microcai.org/2020/04/27/all-device-ipv6ed-and-ddnsed.html) //i.2020/04/27/device-ipv6.

我用openwrt自带的ddns  找了一些网上的脚本,已经能通过mac获取ipv6了并修改cloudflare上绑定的域名的ipv6
脚本如下:
#!/bin/sh
# 这里自己改一下;换成自己设备的MAC;
MAC=00:00:00:00:00:00
PREFIX=$(ip -6 addr show br-lan | grep 'scope global' | awk -F '/|inet6 ' 'NR==1{print $2;}' | sed 's/::.//g')
ip neigh | grep "$MAC" | grep -E "^$PREFIX" | sed 's/ .*//'

**Comment by gdy666** [comment]
v1.7.4 DDNS模块新增自定义指令方式获取IP,可以试试这种方式
