### ISSUE TITLE
lucky与passwall冲突，导致 无法科学上网 / lucky控制后台无法进入 问题

### ISSUE THREAD

**Issue by odean-M** [gdy666/lucky#12]
**我的网络环境：**
- 光猫桥接
- 路由器是AX6S，刷了恩山237大佬的openwrt（这个帖子：https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8187405&highlight=ax6s ），带有passwall科学上网插件
- 移动的网络，只有ipv6公网

**出现过几种场景：**

1. 路由器正常使用passwall过程中，安装lucky配置端口映射（外网33669映射内网80），可通过 <**内网ipv6**环境> 访问 <ddns域名:外网端口号地址> 来访问 <内网设备:映射端口>，但是再去防火墙开放外网映射端口
ip6tables -A INPUT -p tcp --dport 33669 -j ACCEPT
ip6tables -A OUTPUT -p tcp --sport 33669 -j ACCEPT
ip6tables -A FORWARD -p tcp --dport 33669 -j ACCEPT
ip6tables -A INPUT -p udp --dport 33669 -j ACCEPT
ip6tables -A OUTPUT -p udp --sport 33669 -j ACCEPT
ip6tables -A FORWARD -p udp --dport 33669 -j ACCEPT
后，路由器的管理页面变得非常卡、lucky的控制后台 http://192.168.31.1:16601/ 无法进入同时端口映射失效，且passwall无法正常运行、无法科学上网

2. 出现1中情况后路由重启，passwall未启动情况下，进入lucky后台，根据设置的具体端口开放防火墙外网端口，实现了<**外网ipv6**环境> 访问 <ddns域名:外网端口号地址> 来访问 <内网设备:映射端口>，但再开启passwall也无法科学上网，接着连lucky后台也进不去、外网端口映射失效

请问下这种情况有没有什么好的办法呢，我的需求是 科学上网+端口映射 同时使用
（小白一个，描述比较冗余也不专业，感谢看完问题描述）

**Comment by gdy666** [comment]
抱歉,我没使用过passwall,对passwall完全不了解,没法帮得到你.

**Comment by odean-M** [comment]
> 抱歉,我没使用过passwall,对passwall完全不了解,没法帮得到你.

我又试了下openclash，也是类似的情况。似乎科学上网插件跟端口映射类的容易冲突，恩山有一些帖子也出现了这种问题，似乎是TCP端口转发冲突，但是我没找到解决办法

**Comment by gdy666** [comment]
有试过shellclash么?或者你试试不使用ipv6端口映射,而是直接将ipv6防火墙关闭试试.

**Comment by odean-M** [comment]
> 有试过shellclash么?或者你试试不使用ipv6端口映射,而是直接将ipv6防火墙关闭试试.

又折腾了半天，openwrt的无线2.4G会导致家里的小米智能设备都连不上，还是把AX6S刷回了官方固件1.2.7版。装了shellclash，倒是没发现与lucky冲突现象，后台正常进入，ddns任务可以正常进行，但是端口映射没有生效

**Comment by gdy666** [comment]
可能是防火墙问题,我的小米ax6000官方固件,我是把ipv6防火墙都关闭了的...

**Comment by odean-M** [comment]
![image](https://user-images.githubusercontent.com/63239992/192586204-b4d76875-5803-45c7-a381-1cdfcd3afe9d.png)
很奇怪，在官方固件把防火墙关闭后，端口映射还是无效。
又折腾了一下，参考了恩山的帖子，手动在ssh里输入
```
ip6tables -I INPUT -p tcp --dport 33669 -j ACCEPT
ip6tables -I OUTPUT -p tcp --sport 33669 -j ACCEPT
ip6tables -I FORWARD -p tcp --dport 33669 -j ACCEPT
```
开放ipv6端口后终于可以从外网访问了，并且必须是【在防火墙启动】的时候输这几条命令才行，在【防火墙关闭】的情况下输入这几条命令也是不能从外网访问的
想把这几条命令加入rc.local实现开机自动执行，但是又遇见rc.local重启后被清空、权限变回默认的问题（https://www.right.com.cn/forum/thread-8255845-1-1.html）

请问下大佬，有没有可能在lucky里加入开机自启命令行这种，实现端口的自动开放呢

**Comment by gdy666** [comment]
你把这几条命令加在
/data/lucky.daji/scripts/misnap_init.sh
这个的最后面就可以了.

**Comment by odean-M** [comment]
好耶，搞定了！现在哪怕路由重启后也能自动开放端口了，外网顺利访问
我加的内容如下，给遇见相同问题的人作为参考：

sleep 60
#开放ipv6端口
ip6tables -I INPUT -p tcp --dport 50080 -j ACCEPT
ip6tables -I OUTPUT -p tcp --sport 50080 -j ACCEPT
ip6tables -I FORWARD -p tcp --dport 50080 -j ACCEPT
#不知为何如果不重启一次脚本，外放访问时会连接超时
sleep 20
/etc/init.d/lucky.daji restart

**Comment by odean-M** [comment]
感谢大佬

**Comment by odean-M** [comment]
> 你把这几条命令加在 /data/lucky.daji/scripts/misnap_init.sh 这个的最后面就可以了.

大佬牛逼，最近折腾ps5串流，用旧版本的lucky一直搞不定端口转发，升级到1.10.8就行了
