### ISSUE TITLE
遇到CPU长期高占用的情况

### ISSUE THREAD

**Issue by scdlyh** [gdy666/lucky#13]
配置中仅转发了1条 tcp udp 3389端口，其余配置均为默认，版本号为1.3.1版本，多次重启服务器均会出现高占用CPU的情况

![CPU长期高占用](https://user-images.githubusercontent.com/10118910/192137910-6cf517fc-5b1b-4dec-869c-59e055151b14.png)

**Comment by gdy666** [comment]
3389端口 ,这个是windows的远程服务端口么?是的话我得测试一下才能清楚.

**Comment by gdy666** [comment]
1.4.9版本针对端口转发模块有优化,有需要可以试试. 
需要注意的是1.4.9版本需要重新添加转发规则,之前的规则配置会失效.
