### ISSUE TITLE
大佬Dnspod(腾讯云)ipv6解析偶尔会出现问题！

### ISSUE THREAD

**Issue by KoWming** [gdy666/lucky#16]
会出现解析失败，更新域名解析失败:{{ }}
GetBytesFromHttpResponse err:resp.Body = nil

**Comment by gdy666** [comment]
网络方面的原因,偶尔出现无解,你把动态域名设置里面的时间间隔设置小一些,比如60秒,即使一次更新不上也会在下一个检测周期更新上.

**Comment by KoWming** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by KoWming** [comment]
> 网络方面的原因,偶尔出现无解,你把动态域名设置里面的时间间隔设置小一些,比如60秒,即使一次更新不上也会在下一个检测周期更新上.

大佬我发现是因为我的IPV6地址变更后无法同步到Dnspod(腾讯云)导致的，每次出现这样的情况我都只是看了地址前4位和后4位都一样我以为是我的地址没有变化只是刷新了解析，今天注意到中间有一段是不一样的，对比了Alidns(阿里云)的IPV6地址获取记录发现中间的第3段和第4段地址是变化的其他几段地址都一样。不知道是不是因为地址比较相近导致地址变更后无法同步到Dnspod(腾讯云)。
还发现一个问题就是我把Dnspod(腾讯云)的解析记录全部删掉，使用Lucky设置好需要解析的记录提交后无法在Dnspod(腾讯云)自动新建所提交的记录，而Alidns(阿里云)则可以。

**Comment by gdy666** [comment]
是使用1.3.1版本么?之前的版本dnspod有些问题,你要更新到最新的1.3.1版本

**Comment by KoWming** [comment]
> 那就很奇怪了,我这边dnspod正常
> 
> 你用的是Dnspod的Token还是腾讯的API密钥呢?这里使用的应该是dnspod的token.

我使用的是Dnspod的token。
![微信截图_20221006170001](https://user-images.githubusercontent.com/96684377/194270807-6dd0d472-62bc-4641-bfe2-0c677c32d8d4.png)

**Comment by gdy666** [comment]
有需要并且方便的话加我QQ272288813,提供一个临时token我试试?
