### ISSUE TITLE
能不能加一个网络唤醒模块

### ISSUE THREAD

**Issue by cdbvv** [gdy666/lucky#18]
大佬能不能加一个网络唤醒模块，功能实现可以参考https://github.com/helloxz/GoPower

**Comment by gdy666** [comment]
好巧,这是我计划要增加的功能,到时还可以接入点灯物联网平台,实现小爱/小度/天猫精灵语言控制开关机.没写完...等多几天
![QQ截图20221014140406](https://user-images.githubusercontent.com/2849711/195774088-9cca6409-5a34-4c38-91d2-a3d3be33ec57.png)

**Comment by cdbvv** [comment]
我用esp8266加点灯平台实现过,电脑端关机用.net写的。路由器上go语言不会写。。。。js又不支持发送魔术包。点灯科技免费使用对设备数量有要求。你可以看下巴法云，这个好像不怎么限制设备数量

**Comment by gdy666** [comment]
好的,点灯太坑了,文档不全,全靠翻代码,后面会支持多个物联网平台接入.

**Comment by gdy666** [comment]
![QQ截图20221022202243](https://user-images.githubusercontent.com/2849711/197338914-c7a29947-8a3c-4fec-b5cf-3fc9d0a584b1.png)
差不多搞好了...再过一两天...

**Comment by cdbvv** [comment]
牛逼666

**Comment by gdy666** [comment]
1.5.1 已release.
