### ISSUE TITLE
大佬，群晖接主路由，在群晖docker安装后，此软件功能都能用吗？

### ISSUE THREAD

**Issue by yydlh** [gdy666/lucky#19]
比如公网ipv6 端口转发 ipv4内网ip加端口，谢谢，已star

**Comment by gdy666** [comment]
除非你的群晖分配有公网IPv6地址并且外网可以正常访问,否则端口转发和反向代理功能是用不了,只能用得上DDNS动态域名功能.

**Comment by yydlh** [comment]
十分感谢，我已经知晓。反向代理我推荐下nginx  proxy manger ，这个软件可以自动申请ssl，并自动续期。

**Comment by gdy666** [comment]
lucky主要是运行在路由器环境,特点是单文件,执行程序体积小,不是每个路由器环境都有docker或者有太多的存储空间,腾讯云有免费SSL证书,一次申请一年有效.
