### ISSUE TITLE
Lucky 当前版本遇到的问题反馈

### ISSUE THREAD

**Issue by KoWming** [gdy666/lucky#2]
![微信图片_202208020943401](https://user-images.githubusercontent.com/96684377/182273806-421d0659-0b67-4063-aa5b-e7fd9b682078.png)
![微信图片_20220802094340](https://user-images.githubusercontent.com/96684377/182273830-535beefe-e5ea-41b1-beef-f0e6477cebf3.png)
Webhook 配置正确，但是触发回调发送的时候显示失败，是不是我没配置对，还需要在【调用接口成功包含的字符串】框内填写【{"errcode":0,"errmsg":"ok"}】？就现在的Webhook 配置，在推送消息的时候会一次推送两条，即企业微信会同时收到两条域名解析的信息。

**Comment by KoWming** [comment]
![微信图片_202208020943402](https://user-images.githubusercontent.com/96684377/182274887-a7635a42-0721-4ed6-9d41-f8945a54c32d.png)
域名解析过程中还会出现 【子域名负载均衡超出限制】，但是出现问题的域名还是能正常访问。

**Comment by gdy666** [comment]
是的,需要在【调用接口成功包含的字符串】框内填写【{"errcode":0,"errmsg":"ok"}】才会记录为成功回调.
在特定条件下发送两条重复消息的问题会尽快修复.

**Comment by gdy666** [comment]
"子域名负载均衡超出限制"这是dnspod接口反馈的信息,我没在用dnspod,我也不清楚这是什么情况.

**Comment by KoWming** [comment]
> 是的,需要在【调用接口成功包含的字符串】框内填写【{"errcode":0,"errmsg":"ok"}】才会记录为成功回调. 在特定条件下发送两条重复消息的问题会尽快修复.

好的谢谢，回调框内填写了对应参数，Webhook显示正常了！

**Comment by KoWming** [comment]
> "子域名负载均衡超出限制"这是dnspod接口反馈的信息,我没在用dnspod,我也不清楚这是什么情况.

哦，这个暂时没什么影响。主要就是出现解析失败会的提示不影响使用。目前的猜想是我使用的是DNSPod的免费版解析，有可能是子域名过多的原因。

**Comment by gdy666** [comment]
其实并不一定是一次推送了两条信息,只是手动修改或添加DDNS任务后会触发一次同步检查,然后在设定的时间间隔后全部DDNS任务也会触发一次同步检查,当同步检查的时候发现有更新成功域名或更新失败时会触发webhook.两次同步检查间隔太短中都存在更新成功或者更新失败的域名所以触发了两次webhook. 
为了区分是不是真的重复发送消息,会增加多一个变量 #{nowtime},记录触发webhook的时间. 
目前版本的确存在一些没有及时记录域名状态异常的问题,已修复,影响不大,迟些再release了.

**Comment by KoWming** [comment]
> 其实并不一定是一次推送了两条信息,只是手动修改或添加DDNS任务后会触发一次同步检查,然后在设定的时间间隔后全部DDNS任务也会触发一次同步检查,当同步检查的时候发现有更新成功域名或更新失败时会触发webhook.两次同步检查间隔太短中都存在更新成功或者更新失败的域名所以触发了两次webhook. 为了区分是不是真的重复发送消息,会增加多一个变量 #{nowtime},记录触发webhook的时间. 目前版本的确存在一些没有及时记录域名状态异常的问题,已修复,影响不大,迟些再release了.

有这个可能，因为修改或者调试的时候保存了会马上推送，但是今天在我没有调试webhook的情况下我任然收到的是两条推送信息。
![Uploading 微信图片_20220802144856.jpg…]()

**Comment by gdy666** [comment]
1.2.1版应该彻底解决了这个问题,有需要请更新.注意使用新的消息模版.

**Comment by KoWming** [comment]
> 1.2.1版应该彻底解决了这个问题,有需要请更新.注意使用新的消息模版.

好的，能收到你的信息很高兴😃
