### ISSUE TITLE
cloudflare解析失败

### ISSUE THREAD

**Issue by xuecunqwer** [gdy666/lucky#20]
IPV4解析不成功，不知道为啥

**Comment by gdy666** [comment]
麻烦截规则列表或者日志的图我看看?

**Comment by xuecunqwer** [comment]
![image](https://user-images.githubusercontent.com/37589033/195969518-049056d9-9287-4f97-8d15-3a8ac0b30f7d.png)
![image](https://user-images.githubusercontent.com/37589033/195969538-25304d33-a534-4d36-8323-00f7fc07e6c6.png)
![image](https://user-images.githubusercontent.com/37589033/195969550-7677b83e-bfc8-4221-b8a0-57488b3d2253.png)

**Comment by xuecunqwer** [comment]
但是如果我解析好域名了，然后再开启比对是成功的

**Comment by gdy666** [comment]
进cloudflare确定一下你要解析的域名是不是只有一条设置记录,不能存在多条.

**Comment by gdy666** [comment]
或者换条没有解析过的二级域名试试.

**Comment by xuecunqwer** [comment]
我是通过CNNAME来泛域名解析的，
![image](https://user-images.githubusercontent.com/37589033/195969832-ce8e4fdf-aeb3-4d9f-8067-2c8080b227c9.png)
我在域名解析里设置的是解析WWW.XXXX.XXX

**Comment by xuecunqwer** [comment]
但是我需要设置泛域名解析，然后反向代理

**Comment by gdy666** [comment]
直接在域名列表里面填
*.xxx.com就好了呀,不需要CNAME.

**Comment by xuecunqwer** [comment]
好的。。谢谢，我试试

**Comment by xuecunqwer** [comment]
按你的方法试了，还是解析失败，我本地的解析我也真的*.XXX.COM是对的吧

**Comment by xuecunqwer** [comment]
哦，不过我有两条解析记录，不能这么用是吧，那没办法用不了这个了

**Comment by gdy666** [comment]
你要在lucky同步*.XXX.com的A记录的话,你得把那条*.XXX.com的CNAME记录删除吧
如果你没理解,你试试在lucky设置条三级解析域名
*.a.XXX.com 看看能否成功

**Comment by xuecunqwer** [comment]
我已经删除了，我现在CF解析记录里就就一条，*.XXX.COM
然后本地解析也就设置了*.xxx.com

**Comment by gdy666** [comment]
那就奇怪了,我这边一直在使用cloudfalre.
![QQ截图20221015141417](https://user-images.githubusercontent.com/2849711/195972128-f1a65e44-7e9b-42cc-aef9-d79e0a2a5a7a.png)

**Comment by xuecunqwer** [comment]
是不是V4和V6不太一样？

**Comment by xuecunqwer** [comment]
我用OP里的动态DNS没问题

**Comment by gdy666** [comment]
不一定,这部分代码是来自ddns-go,待我想想如何重现你这种失败情况.

**Comment by gdy666** [comment]
我貌似重现了,你要使用*.XXX.com的话,
你得把cloudflare里面所有明确的二级域名删除,
或者直接在域名列表添加多条二级域名代替泛解析.

**Comment by xuecunqwer** [comment]
我只解析一条记录都不行，其它的我都删了，只留了*.xxx.com

**Comment by gdy666** [comment]
那就暂时只能只能直接在域名列表添加多条二级域名代替泛解析.
这是ddns-go的同步处理限制,我暂时也没时间去研究理解为啥他这样处理...

**Comment by xuecunqwer** [comment]
DDNS-GO我也没成功过，所以我用的“动态DNS”

**Comment by gdy666** [comment]
![QQ截图20221015143645](https://user-images.githubusercontent.com/2849711/195973077-dba62a5b-51b6-44af-810d-dd0a68941973.png)
CNAME记录影响了,把所有记录都删除了在同步.

**Comment by xuecunqwer** [comment]
是的，我刚这么做过了

**Comment by gdy666** [comment]
你截一下你现在在cloudflare的DNS记录列表我看看?

**Comment by xuecunqwer** [comment]
![image](https://user-images.githubusercontent.com/37589033/195973293-7e663241-e825-4919-b899-fe71d05fd580.png)
![image](https://user-images.githubusercontent.com/37589033/195973297-a5185359-8e3b-4257-b76f-de2039cb396b.png)

**Comment by gdy666** [comment]
把这条也删除了再去同步试试?

**Comment by xuecunqwer** [comment]
不行，还是失败

**Comment by gdy666** [comment]
我这边ipv4/ipv6的泛解析都是正常的.除非你加我QQ,提供token我测试一下,要不然无解了...

**Comment by xuecunqwer** [comment]
没事了，先用别的吧，看看其它人有没有这问题吧

**Comment by gdy666** [comment]
你看看你的是不是这种问题.
https://github.com/jeessy2/ddns-go/issues/62

**Comment by xuecunqwer** [comment]
我不是这个问题，用另一个解析就行，但是这个不行
