### ISSUE TITLE
能否添加自动更新

### ISSUE THREAD

**Issue by 596142041** [gdy666/lucky#22]
能否添加自动更新或者通过脚本实现自动更新

**Comment by gdy666** [comment]
是有这样的计划,但短期内未必会加入,麻烦等待一下.

**Comment by hmy1210** [comment]
> 是有这样的计划,但短期内未必会加入,麻烦等待一下.

顺带来一句。不知道是否会有可能写个luci，不一定就是在luci上有什么功能，可以类似homebox那样，提示状态和打开ui地址
![image](https://user-images.githubusercontent.com/30746089/196114869-47f93d89-1386-4b46-97d2-fd9d006e87a8.png)

**Comment by gdy666** [comment]
> > 是有这样的计划,但短期内未必会加入,麻烦等待一下.
> 
> 顺带来一句。不知道是否会有可能写个luci，不一定就是在luci上有什么功能，可以类似homebox那样，提示状态和打开ui地址 ![image](https://user-images.githubusercontent.com/30746089/196114869-47f93d89-1386-4b46-97d2-fd9d006e87a8.png)

有大神写好了,可以参考一下.
https://github.com/sirpdboy/luci-app-lucky
我自己暂时就没啥时间精力折腾编译openwrt了...

**Comment by 596142041** [comment]
> > 是有这样的计划,但短期内未必会加入,麻烦等待一下.
> 
> 顺带来一句。不知道是否会有可能写个luci，不一定就是在luci上有什么功能，可以类似homebox那样，提示状态和打开ui地址 ![image](https://user-images.githubusercontent.com/30746089/196114869-47f93d89-1386-4b46-97d2-fd9d006e87a8.png)
UI已经有人做了，可以参考一下下面的链接，已经在使用了，很方便
