### ISSUE TITLE
请问ipv6 IPTV使用场景是否可以

### ISSUE THREAD

**Issue by AbsoluteRay** [gdy666/lucky#25]
背景是这样：我的电视不支持IPV6，是否可以通过lucy实现转发ipv6流量观看IPTV呢

**Comment by gdy666** [comment]
理论上只要是基于tcp/udp协议都可以支持,可以提供iptv地址我测试一下.
目前版本ipv4端口转ipv6有些问题,需要等稍后发布的新版本修复.

**Comment by AbsoluteRay** [comment]
> 理论上只要是基于tcp/udp协议都可以支持,可以提供iptv地址我测试一下. 目前版本ipv4端口转ipv6有些问题,需要等稍后发布的新版本修复.

来自twitter @MateCafe提供的地址，
https://raw.githubusercontent.com/YueChan/IPTV/main/IPTV.m3u

使用iOS APTV观看都是秒打开。然而我的电视系统不支持ipv6无法从路由器获取到ipv6地址无法观看

**Comment by gdy666** [comment]
![QQ截图20221113020005](https://user-images.githubusercontent.com/2849711/201488217-4f6f61e8-98c1-4c0d-9561-027e74ee11ad.png)
我测试了湖南卫视的,2409:8087:3869:8021:1001::e5这个,可以使用.

**Comment by gdy666** [comment]
![QQ截图20221113020244](https://user-images.githubusercontent.com/2849711/201488292-9c9f53a7-4c99-4a29-9e84-2e96aa8a5b36.png)
连接地址就改为lucky的ipv4内网地址和端口

**Comment by gdy666** [comment]
我测试了一下,
![QQ截图20221113020005](https://user-images.githubusercontent.com/2849711/201488844-a40798e6-1a14-4dfb-b1d6-f3bcde55752e.png)
除了建立端口规则规则以外你还得修改m3u文件里面的服务器信息,然后不知啥原因只能播放几十秒.
太麻烦了,没研究过m3u原理,可以放弃这种方式了.

**Comment by gdy666** [comment]
大概猜到了原理,m3u文件动态生成只保存的一段很 小时间内的缓存地址,播放完重新读取生成新的缓存地址,不是单纯设置端口转发就可以实现的转发的.

**Comment by AbsoluteRay** [comment]
> 我测试了一下, ![QQ截图20221113020005](https://user-images.githubusercontent.com/2849711/201488844-a40798e6-1a14-4dfb-b1d6-f3bcde55752e.png) 除了建立端口规则规则以外你还得修改m3u文件里面的服务器信息,然后不知啥原因只能播放几十秒. 太麻烦了,没研究过m3u原理,可以放弃这种方式了.

我按照这个配置，在电视上试着打开m3u，但是lucky没有感知到任何连接或流量，不知道原因。
![image](https://user-images.githubusercontent.com/3929067/201502465-bf0e4c93-10ed-4e55-9b93-4e5c63269aee.png)
![image](https://user-images.githubusercontent.com/3929067/201502473-85b39566-c847-48a1-992b-3fa27bae881a.png)

**Comment by AbsoluteRay** [comment]
> 大概猜到了原理,m3u文件动态生成只保存的一段很 小时间内的缓存地址,播放完重新读取生成新的缓存地址,不是单纯设置端口转发就可以实现的转发的.

但这里至少证明了可以成功转发到非ipv6设备上吧

**Comment by gdy666** [comment]
> > 大概猜到了原理,m3u文件动态生成只保存的一段很 小时间内的缓存地址,播放完重新读取生成新的缓存地址,不是单纯设置端口转发就可以实现的转发的.
> 
> 但这里至少证明了可以成功转发到非ipv6设备上吧

嗯,需要动态拦截修改m3u请求返回内容里面的服务器地址信息,太麻烦了.

**Comment by AbsoluteRay** [comment]
> > > 大概猜到了原理,m3u文件动态生成只保存的一段很 小时间内的缓存地址,播放完重新读取生成新的缓存地址,不是单纯设置端口转发就可以实现的转发的.
> > 
> > 
> > 但这里至少证明了可以成功转发到非ipv6设备上吧
> 
> 嗯,需要动态拦截修改m3u请求返回内容里面的服务器地址信息,太麻烦了.

这个就类似于手机上URL REWRITE吗，大神有没有思路在路由器上可以怎样实现，给个大概方向。

**Comment by gdy666** [comment]
没接触过
