### ISSUE TITLE
期待类似NPM的SSL证书自动续订功能。

### ISSUE THREAD

**Issue by a18ccms** [gdy666/lucky#26]
NPM自动续订功能是我都刚需，LUCKY已经功能很强大了。就是暂时没看到这个功能，期待大佬开发这个功能。我就可以放弃NPM了。

**Comment by gdy666** [comment]
有计划加入https://github.com/go-acme/lego 这个的SSL证书续订功能.

**Comment by a18ccms** [comment]
期待更新，作者辛苦！
