### ISSUE TITLE
请问openwrt下源码编译需要哪些依赖？我编译时候出现依赖缺失，见日志！

### ISSUE THREAD

**Issue by zxlhhyccc** [gdy666/lucky#27]
请问该依赖在Makefile下如何写？谢谢！
`````
install -m0644 ./files/lucky-default.conf /home/lin/ax6/build_dir/target-aarch64_cortex-a53_musl/lucky-1.5.1/ipkg-aarch64_cortex-a53/lucky/etc/lucky/lucky-default.conf
find /home/lin/ax6/build_dir/target-aarch64_cortex-a53_musl/lucky-1.5.1/ipkg-aarch64_cortex-a53/lucky -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package lucky is missing dependencies for the following libraries:
libc.so.6
libpthread.so.0
Makefile:95: recipe for target '/home/lin/ax6/bin/packages/aarch64_cortex-a53/base/lucky_1.5.1-2_aarch64_cortex-a53.ipk' failed
make[2]: *** [/home/lin/ax6/bin/packages/aarch64_cortex-a53/base/lucky_1.5.1-2_aarch64_cortex-a53.ipk] Error 1
make[2]: Leaving directory '/home/lin/bf-package-master/zxlhhyccc/ddns-go/lucky'
time: package/bf-package-master/zxlhhyccc/ddns-go/lucky/compile#1.46#1.14#1.99
    ERROR: package/bf-package-master/zxlhhyccc/ddns-go/lucky failed to build.
package/Makefile:114: recipe for target 'package/bf-package-master/zxlhhyccc/ddns-go/lucky/compile' failed
make[1]: *** [package/bf-package-master/zxlhhyccc/ddns-go/lucky/compile] Error 1
make[1]: Leaving directory '/home/lin/ax6'
/home/lin/ax6/include/toplevel.mk:229: recipe for target 'package/lucky/compile' failed
make: *** [package/lucky/compile] Error 2
`````

**Comment by gdy666** [comment]
https://github.com/sirpdboy/luci-app-lucky 这个的编译问题你应该找它的作者,我好多年都没编译过openwrt了.
 openwrt编译依赖的话我找了找以前的笔记,看看你能否用得上.

CentOS:
yum install asciidoc libgcj flex git-core gcc-c++ gtk2-devel intltool make ncurses-devel openssl-devel perl-ExtUtils-MakeMaker python-devel ruby unzip wget subversion  sqlite-devel
 
Ubuntu :
sudo apt-get install asciidoc bash binutils bzip2 fastjar flex git-core g++ gcc util-linux gawk  intltool libgtk2.0-dev zlib1g-dev make libncurses5-dev libssl-dev patch perl-modules rsync ruby sdcc unzip wget gettext xsltproc zlib1g-dev python-dev bison subversion cmake

**Comment by zxlhhyccc** [comment]
> https://github.com/sirpdboy/luci-app-lucky 这个的编译问题你应该找它的作者,我好多年都没编译过openwrt了. openwrt编译依赖的话我找了找以前的笔记,看看你能否用得上.
> 
> CentOS: yum install asciidoc libgcj flex git-core gcc-c++ gtk2-devel intltool make ncurses-devel openssl-devel perl-ExtUtils-MakeMaker python-devel ruby unzip wget subversion  sqlite-devel   Ubuntu : sudo apt-get install asciidoc bash binutils bzip2 fastjar flex git-core g++ gcc util-linux gawk  intltool libgtk2.0-dev zlib1g-dev make libncurses5-dev libssl-dev patch perl-modules rsync ruby sdcc unzip wget gettext xsltproc zlib1g-dev python-dev bison subversion cmake

我openwrt通过Makefile编译，提示缺少libc.so.6、libpthread.so.0链接库，不是你说的安装依赖包。

**Comment by gdy666** [comment]
https://github.com/sirpdboy/luci-app-lucky 我稍微看了一下这个项目,它并没有对lukcy源码进行编译,只是根据不同平台下载现成的二进制程序包,所以应该不是lucky的问题...或者等我尝试编译一下ipk包再回复你.

**Comment by zxlhhyccc** [comment]
> https://github.com/sirpdboy/luci-app-lucky 我稍微看了一下这个项目,它并没有对lukcy源码进行编译,只是根据不同平台下载现成的二进制程序包,所以应该不是lucky的问题...或者等我尝试编译一下ipk包再回复你.

好的，我的意思就是直接源码编译二进制出来。。。但显示需要上述链接库，而一般情况下是不会编译出来上述链接库的，如果需有上述链接库，必须选择``EXTERNAL_TOOLCHAIN``，才能在libc和libpthread选择``LIBC_FILE_SPEC``和``LIBPTHREAD_FILE_SPEC``，这个时候我不知道怎么写了！

**Comment by zxlhhyccc** [comment]
> 哈哈哈,openwrt怎么直接从golang源码直接编译我也不会...

仓库里写了这个：``go build -v -tags "adminweb nomsgpack" -ldflags="-s -w"``

**Comment by zxlhhyccc** [comment]
> golang 编译的,openwrt 如果要编译golang程序的源码 ipk包makefile的写法和C/C++源码有出入,还是直接用二进制程序少折腾一些.并且源码我只开发到了一个月前的版本.

请教大佬，你仓库的二进制是怎么出来的？能给一些你编译的配置信息吗？

**Comment by gdy666** [comment]
https://go.dev/dl/ 
首先你得懂golang,安装golang开发环境,设置好gopath各种之类的环境变量...然后执行那条编译命令

**Comment by gdy666** [comment]
参考我上面的makefile,我编译x86_64平台正常.

**Comment by gdy666** [comment]
在openwrt的软件库里面随便找个同样是golang源码的项目照着改改就成了.

**Comment by zxlhhyccc** [comment]
> 在openwrt的软件库里面随便找个同样是golang源码的项目照着改改就成了.

按照你的Makefile编译到这里出问题。。。
![image](https://user-images.githubusercontent.com/45259624/202741241-52192ce9-c7ad-4f15-b69d-d1b4db70d3b4.png)

**Comment by gdy666** [comment]
> > 在openwrt的软件库里面随便找个同样是golang源码的项目照着改改就成了.
> 
> 按照你的Makefile编译到这里出问题。。。 ![image](https://user-images.githubusercontent.com/45259624/202741241-52192ce9-c7ad-4f15-b69d-d1b4db70d3b4.png)

这个是正常的了,你 fork一份代码,然后把debug.go这个文件删除应该就可以了,makefile改为你的fork的地址试试.

不知道为什么openwrt 的golang把debug.go也编译进去了,由于不是每个架构linux交叉编译工具链都是这个函数名称.所以才出了这个问题..

**Comment by zxlhhyccc** [comment]
> debug.go

debug.go文件就在根目录下，我删除了还是一样的错误。。。。

**Comment by gdy666** [comment]
> > debug.go
> 
> debug.go文件就在根目录下，我删除了还是一样的错误。。。。

你把你fork修改后的仓库地址和makefile发出来看看

**Comment by zxlhhyccc** [comment]
> 

https://github.com/zxlhhyccc/goports

**Comment by gdy666** [comment]
你修改的makefile也发一下

**Comment by zxlhhyccc** [comment]
> 你修改的makefile也发一下

我直接用的是你的Makefile，我先没动。。。

**Comment by gdy666** [comment]
> PKG_SOURCE_UR

你不修改PKG_SOURCE_URL和PKG_HASH 能对得上你仓库?你玩我呢....

**Comment by zxlhhyccc** [comment]
> > PKG_SOURCE_UR
> 
> 你不修改PKG_SOURCE_URL和PKG_HASH 能对得上你仓库?你玩我呢....

我直接打的补丁处理，没用我的仓库。

**Comment by zxlhhyccc** [comment]
`````
--- a/debug.go
+++ /dev/null
@@ -1,21 +0,0 @@
-//go:build debug
-// +build debug
-
-package main
-
-import (
-	"fmt"
-
-	"github.com/gdy666/lucky/thirdlib/gdylib/recoverutil"
-)
-
-func init() {
-	defer func() {
-		recoverErr := recover()
-		if recoverErr == nil {
-			return
-		}
-		panicFile := fmt.Sprintf("闪退.log")
-		recoverutil.RecoverHandler(recoverErr, true, true, panicFile)
-	}()
-}
``````

**Comment by gdy666** [comment]
随便改就行了,主要给我自己在很少几率下windows和x86_64的linux调试使用.
其它架构平台懒得适配

**Comment by gdy666** [comment]
正常编译是不会把这个文件编译进去的,不知道openwrt 的makfile还有哪里不对,我才不折腾呢...

**Comment by zxlhhyccc** [comment]
````
--- a/thirdlib/gdylib/stderrredirect/stderrredirect_linux.go
+++ b/thirdlib/gdylib/stderrredirect/stderrredirect_linux.go
@@ -39,9 +39,6 @@ func PanicRedirect(fileURL string) {
 		if err != nil {
 			return
 		}
-		if err = syscall.Dup2(int(file.Fd()), int(os.Stderr.Fd())); err != nil {
-			return
-		}
 		return
 	})
 ````
````
--- a/thirdlib/gdylib/stderrredirect/stderrredirect_linux.go
+++ b/thirdlib/gdylib/stderrredirect/stderrredirect_linux.go
@@ -5,7 +5,6 @@ import (
 	"os"
 	"strings"
 	"sync"
-	"syscall"
 
 	"github.com/gdy666/lucky/thirdlib/gdylib/fileutils"
 )
`````

**Comment by gdy666** [comment]
> > 不会有影响,主要用来调试捕捉极端情况下的一时半刻找不出的崩溃错误,至今都没用得上,发布版本是不会有这个的.
> 
> 1.6.1版本怎么download不下来？

都说了我没同步最新源码上去,tags是1.6.1也不代表是1.6.1版本
另外pkg_hash你要改吧
并且你

**Comment by gdy666** [comment]
论到我提问了,
有没啥办法让编译出来的指定平台的ipk包里面的control.tar.gz里面的control文件的
Architecture: arm_cortex-a15_neon-vfpv4
改为
Architecture: all?

**Comment by zxlhhyccc** [comment]
> 论到我提问了, 有没啥办法让编译出来的指定平台的ipk包里面的control.tar.gz里面的control文件的 Architecture: arm_cortex-a15_neon-vfpv4 改为 Architecture: all?

编译出来的有11.1m，能压缩吗？

**Comment by gdy666** [comment]
> > 论到我提问了, 有没啥办法让编译出来的指定平台的ipk包里面的control.tar.gz里面的control文件的 Architecture: arm_cortex-a15_neon-vfpv4 改为 Architecture: all?
> 
> 啥意思啊？你是指这个吗？ ![image](https://user-images.githubusercontent.com/45259624/202755933-8b617f11-072f-48b4-95f0-015ea1df7cd2.png)

是这个,我想让他编译出来的
Architecture: armXXXX
这行显示成Architecture: all

**Comment by gdy666** [comment]
> > 论到我提问了, 有没啥办法让编译出来的指定平台的ipk包里面的control.tar.gz里面的control文件的 Architecture: arm_cortex-a15_neon-vfpv4 改为 Architecture: all?
> 
> 编译出来的有11.1m，能压缩吗？

用UPX压缩,至于怎么将upx自动化压缩写进makefile我也不懂

**Comment by gdy666** [comment]
我用golang把ipk解包替换不同架构的lucky文件再封装生成不同平台的ipk,现在卡在了control.tar.gz这里,即使我对这个文件什么都不改动,ipk安装依然会出现错误,不知哪出了问题.
![QQ截图20221119004626](https://user-images.githubusercontent.com/2849711/202757679-8bcb7689-631d-408b-88ea-51236b7737a0.png)

**Comment by zxlhhyccc** [comment]
> 我用golang把ipk解包替换不同架构的lucky文件再封装生成不同平台的ipk,现在卡在了control.tar.gz这里,即使我对这个文件什么都不改动,ipk安装依然会出现错误,不知哪出了问题. ![QQ截图20221119004626](https://user-images.githubusercontent.com/2849711/202757679-8bcb7689-631d-408b-88ea-51236b7737a0.png)

带压缩的Makefile：
```
include $(TOPDIR)/rules.mk

PKG_NAME:=lucky
PKG_VERSION:=1.5.1
PKG_RELEASE:=$(AUTORELEASE)

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/gdy666/lucky/tar.gz/v$(PKG_VERSION)
PKG_HASH:=03111d4a234a9526fa99f2f480b6afc8ad0e03c2600796b694e63de5aaf3bef8

PKG_LICENSE:=AGPL-3.0-only
PKG_LICENSE_FILES:=LICENSE

PKG_CONFIG_DEPENDS:= \
	CONFIG_LUCKY_COMPRESS_GOPROXY \
	CONFIG_LUCKY_COMPRESS_UPX

PKG_BUILD_DEPENDS:=golang/host
PKG_BUILD_PARALLEL:=1
PKG_USE_MIPS16:=0

GO_PKG:=github.com/gdy666/lucky
GO_PKG_LDFLAGS:=-s -w
GO_PKG_LDFLAGS_X:=main.Version=v$(PKG_VERSION)

include $(INCLUDE_DIR)/package.mk
include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk

define Package/lucky
TITLE:=Lucky dynamic domain name ddns-go service, socat,frp
SECTION:=net
CATEGORY:=Network
SUBMENU:=Web Servers/Proxies
DEPENDS:=$(GO_ARCH_DEPENDS)
URL:=https://github.com/gdy666/lucky
endef

define Package/$(PKG_NAME)/description
Main functions of Lucky: dynamic domain name ddns-go service, socat,frp
endef

define Package/$(PKG_NAME)/config
config LUCKY_COMPRESS_GOPROXY
	bool "Compiling with GOPROXY proxy"
	default n

config LUCKY_COMPRESS_UPX
	bool "Compress executable files with UPX"
	depends on !mips64
	default n
endef

ifeq ($(CONFIG_LUCKY_COMPRESS_GOPROXY),y)
	export GO111MODULE=on
	export GOPROXY=https://goproxy.baidu.com
endif

define Build/Compile
	$(call GoPackage/Build/Compile)
ifneq ($(CONFIG_LUCKY_COMPRESS_UPX),)
	$(STAGING_DIR_HOST)/bin/upx --lzma --best $(GO_PKG_BUILD_BIN_DIR)/lucky
endif
endef

define Package/$(PKG_NAME)/install
	$(call GoPackage/Package/Install/Bin,$(1))

	$(INSTALL_DIR) $(1)/etc/init.d $(1)/etc/uci-defaults
	$(INSTALL_BIN) ./files/lucky.init $(1)/etc/init.d/lucky
	$(INSTALL_BIN) ./files/luci-lucky.uci-default $(1)/etc/uci-defaults/luci-lucky
endef

$(eval $(call GoBinPackage,lucky))
$(eval $(call BuildPackage,lucky))
``````

**Comment by gdy666** [comment]
> > 我用golang把ipk解包替换不同架构的lucky文件再封装生成不同平台的ipk,现在卡在了control.tar.gz这里,即使我对这个文件什么都不改动,ipk安装依然会出现错误,不知哪出了问题. ![QQ截图20221119004626](https://user-images.githubusercontent.com/2849711/202757679-8bcb7689-631d-408b-88ea-51236b7737a0.png)
> 
> 带压缩的Makefile：
> 
> ```
> include $(TOPDIR)/rules.mk
> 
> PKG_NAME:=lucky
> PKG_VERSION:=1.5.1
> PKG_RELEASE:=$(AUTORELEASE)
> 
> PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
> PKG_SOURCE_URL:=https://codeload.github.com/gdy666/lucky/tar.gz/v$(PKG_VERSION)
> PKG_HASH:=03111d4a234a9526fa99f2f480b6afc8ad0e03c2600796b694e63de5aaf3bef8
> 
> PKG_LICENSE:=AGPL-3.0-only
> PKG_LICENSE_FILES:=LICENSE
> 
> PKG_CONFIG_DEPENDS:= \
> 	CONFIG_LUCKY_COMPRESS_GOPROXY \
> 	CONFIG_LUCKY_COMPRESS_UPX
> 
> PKG_BUILD_DEPENDS:=golang/host
> PKG_BUILD_PARALLEL:=1
> PKG_USE_MIPS16:=0
> 
> GO_PKG:=github.com/gdy666/lucky
> GO_PKG_LDFLAGS:=-s -w
> GO_PKG_LDFLAGS_X:=main.Version=v$(PKG_VERSION)
> 
> include $(INCLUDE_DIR)/package.mk
> include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk
> 
> define Package/lucky
> TITLE:=Lucky dynamic domain name ddns-go service, socat,frp
> SECTION:=net
> CATEGORY:=Network
> SUBMENU:=Web Servers/Proxies
> DEPENDS:=$(GO_ARCH_DEPENDS)
> URL:=https://github.com/gdy666/lucky
> endef
> 
> define Package/$(PKG_NAME)/description
> Main functions of Lucky: dynamic domain name ddns-go service, socat,frp
> endef
> 
> define Package/$(PKG_NAME)/config
> config LUCKY_COMPRESS_GOPROXY
> 	bool "Compiling with GOPROXY proxy"
> 	default n
> 
> config LUCKY_COMPRESS_UPX
> 	bool "Compress executable files with UPX"
> 	depends on !mips64
> 	default n
> endef
> 
> ifeq ($(CONFIG_LUCKY_COMPRESS_GOPROXY),y)
> 	export GO111MODULE=on
> 	export GOPROXY=https://goproxy.baidu.com
> endif
> 
> define Build/Compile
> 	$(call GoPackage/Build/Compile)
> ifneq ($(CONFIG_LUCKY_COMPRESS_UPX),)
> 	$(STAGING_DIR_HOST)/bin/upx --lzma --best $(GO_PKG_BUILD_BIN_DIR)/lucky
> endif
> endef
> 
> define Package/$(PKG_NAME)/install
> 	$(call GoPackage/Package/Install/Bin,$(1))
> 
> 	$(INSTALL_DIR) $(1)/etc/init.d $(1)/etc/uci-defaults
> 	$(INSTALL_BIN) ./files/lucky.init $(1)/etc/init.d/lucky
> 	$(INSTALL_BIN) ./files/luci-lucky.uci-default $(1)/etc/uci-defaults/luci-lucky
> endef
> 
> $(eval $(call GoBinPackage,lucky))
> $(eval $(call BuildPackage,lucky))
> ```

你试过你能用就行了,我懒得试...

**Comment by zxlhhyccc** [comment]
> 我用golang把ipk解包替换不同架构的lucky文件再封装生成不同平台的ipk,现在卡在了control.tar.gz这里,即使我对这个文件什么都不改动,ipk安装依然会出现错误,不知哪出了问题. ![QQ截图20221119004626](https://user-images.githubusercontent.com/2849711/202757679-8bcb7689-631d-408b-88ea-51236b7737a0.png)

你直接改control？

**Comment by zxlhhyccc** [comment]
> 你试过你能用就行了,我懒得试...

我来测试一下看能不能运行。。。

**Comment by gdy666** [comment]
> > 我用golang把ipk解包替换不同架构的lucky文件再封装生成不同平台的ipk,现在卡在了control.tar.gz这里,即使我对这个文件什么都不改动,ipk安装依然会出现错误,不知哪出了问题. ![QQ截图20221119004626](https://user-images.githubusercontent.com/2849711/202757679-8bcb7689-631d-408b-88ea-51236b7737a0.png)
> 
> 你直接改control？

即使我不改动,原封不懂解包读数据原封不懂再压缩也不行......

**Comment by zxlhhyccc** [comment]
> > > 我用golang把ipk解包替换不同架构的lucky文件再封装生成不同平台的ipk,现在卡在了control.tar.gz这里,即使我对这个文件什么都不改动,ipk安装依然会出现错误,不知哪出了问题. ![QQ截图20221119004626](https://user-images.githubusercontent.com/2849711/202757679-8bcb7689-631d-408b-88ea-51236b7737a0.png)
> > 
> > 
> > 你直接改control？
> 
> 即使我不改动,原封不动解包读数据原封不懂再压缩也不行......

![image](https://user-images.githubusercontent.com/45259624/202758821-fe1a6556-bed7-4d17-a73b-fc32c2331590.png)
是这个影响吧？你强制安装试试？

**Comment by gdy666** [comment]
哎,不是这个问题,golang处理程序有处地方顺序写错...坑了我两天的问题终于解决,
只需一个平台的ipk包,然后替换lucky生成多平台ipk包貌似搞掂...

**Comment by zxlhhyccc** [comment]
> 哎,不是这个问题,golang处理程序有处地方顺序写错...坑了我两天的问题终于解决, 只需一个平台的ipk包,然后替换lucky生成多平台ipk包貌似搞掂...

参考这个，一个ipk就搞定多平台：https://github.com/pymumu/smartdns

**Comment by zxlhhyccc** [comment]
> 哎,不是这个问题,golang处理程序有处地方顺序写错...坑了我两天的问题终于解决, 只需一个平台的ipk包,然后替换lucky生成多平台ipk包貌似搞掂...

源码里写错了？

**Comment by zxlhhyccc** [comment]
大佬，有打算把最新源码放上来吗？

**Comment by gdy666** [comment]
> 大佬，有打算把最新源码放上来吗？

暂时没这打算,可能开放源码就停留在当前版本了.

**Comment by zxlhhyccc** [comment]
> > 大佬，有打算把最新源码放上来吗？
> 
> 暂时没这打算,可能开放源码就停留在当前版本了.

大佬，为啥不开放源码呢？

**Comment by gdy666** [comment]
我记得在https://github.com/sirpdboy/luci-app-lucky/issues/7 这里回答过你同样问题.makefile没问题就close了.
