### ISSUE TITLE
Lucky大吉无法启动

### ISSUE THREAD

**Issue by BlueDolphin9527** [gdy666/lucky#28]
使用的是Sirpdboy11月11日大全版VIP固件，刚配置好Lucky大吉时，能正常使用，但过一段时间，就再也无法启动Lucky大吉了，在Sirpdboy1025极致版VIP固件里也遇到过这个问题。和Sirpdboy沟通过，他讲只是应您邀请做了这个LCUI插件移植到OPENWRT，要我找您反馈。最后附上插件版本号截图和录制问题的gif图片。
希望开发者大大能尽快修复好这个bug。
![Lucky大吉](https://user-images.githubusercontent.com/62049321/201662050-ddeae8be-4562-4f9c-9b17-b45caccd563a.gif)
<img width="1381" alt="Lucky插件说明" src="https://user-images.githubusercontent.com/62049321/201662069-3adc9576-51c5-4b0b-bedb-57b618df2e63.png">

**Comment by gdy666** [comment]
方便的话可以先加我QQ远程连接SSH看一下,或者等我自己编译ipk在openwrt测试一下...因为我主要都是用脚本安装的方式启动,暂时你是第一个跟我反馈lucky没法启动的,所以估计是luci插件哪里的设置有问题,我得搞清楚先.

**Comment by zxlhhyccc** [comment]
> 方便的话可以先加我QQ远程连接SSH看一下,或者等我自己编译ipk在openwrt测试一下...因为我主要都是用脚本安装的方式启动,暂时你是第一个跟我反馈lucky没法启动的,所以估计是luci插件哪里的设置有问题,我得搞清楚先.

openwrt下可以正常启动，没有问题的。。。

**Comment by BlueDolphin9527** [comment]
> > 方便的话可以先加我QQ远程连接SSH看一下,或者等我自己编译ipk在openwrt测试一下...因为我主要都是用脚本安装的方式启动,暂时你是第一个跟我反馈lucky没法启动的,所以估计是luci插件哪里的设置有问题,我得搞清楚先.
> 
> openwrt下可以正常启动，没有问题的。。。

所以我才说，我是遇到bug了啊。如果所有openwrt都不能启动，那就不是bug，是设计问题了。

**Comment by BlueDolphin9527** [comment]
> 方便的话可以先加我QQ远程连接SSH看一下,或者等我自己编译ipk在openwrt测试一下...因为我主要都是用脚本安装的方式启动,暂时你是第一个跟我反馈lucky没法启动的,所以估计是luci插件哪里的设置有问题,我得搞清楚先.

嗯，我没找到你的QQ，你加我吧，1640854278
