### ISSUE TITLE
端口转发能不能同时打开防火墙端口

### ISSUE THREAD

**Issue by skill7899** [gdy666/lucky#29]
目前需要手动添加ipv6的防火墙放行端口

**Comment by gdy666** [comment]
我是直接关闭ipv6防火墙的o(╯□╰)o
考虑到多平台不同系统环境的不同情况,太麻烦了,暂时不考虑这个...

**Comment by skill7899** [comment]
> 我是直接关闭ipv6防火墙的o(╯□╰)o 考虑到多平台不同系统环境的不同情况,太麻烦了,暂时不考虑这个...

不多吧，一般都是iptable和ntftable

**Comment by skill7899** [comment]
go写的转发，真是very good。用协程大大减少内存

**Comment by gdy666** [comment]
你提供一下相关iptable和ntftable 开放禁用端口的例子,让我想想怎么加上去好.

**Comment by skill7899** [comment]
iptalbes可以用以下命令
ip6tables -A INPUT -p tcp --dport 22 -j ACCEPT    #允许访问22端口
ip6tables -A INPUT -p udp --dport 22 -j ACCEPT  #允许访问22端口

nftables有点麻烦。
https://www.jianshu.com/p/eec25be9c5be
