### ISSUE TITLE
挺好用的，但是有点小问题

### ISSUE THREAD

**Issue by snail2sky** [gdy666/lucky#3]
程序是可以同步更新ip到指定的域名，但是调用godaddy 成功后 是没有任何信息的，然后你的程序就认为是同步失败，因为我没有设置接口调用成功的字符串
如果用户未填写任何调用成功的信息，应该认为如果没有任何信息，那么就是同步成功

**Comment by snail2sky** [comment]
貌似有不小的问题，测试过程中，当服务所在的机器IP发生变化时，30秒后并没有去指定的dns服务商同步 新的ip，只有当手动点击 修改，然后保存才会去做这个同步操作，

**Comment by gdy666** [comment]
好的,收到,过几天会加上,这两天在重构ddns部分内容所以不会太快加上

**Comment by snail2sky** [comment]
> n

OK，刚才那个PR，可以在前端加个说明：如果不写，就认为接口无信息返回即为成功
有的服务商接口调用成功就是没有信息，没信息就表示成功

**Comment by gdy666** [comment]
![QQ截图20220807111126](https://user-images.githubusercontent.com/2849711/183273384-8f71acd5-1ed4-4723-b4de-09bb8c954185.png)
加个开关,如果不禁用成功调用字符串检测的同时用户又不填写字符串的话会弹出提示.
禁用检测后就仅以StatusCode== http.StatusOK 作为接口成功调用的判断.
另外有时间的话麻烦把godaddy 的参数模版发一份给我,我添加进前端模版里面?

**Comment by snail2sky** [comment]
好的 我可以试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月7日(周日) 中午11:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gdy666/lucky] 挺好用的，但是有点小问题 (Issue #3)




 

 加个开关,如果不禁用成功调用字符串检测的同时用户又不填写字符串的话会弹出提示.
 禁用检测后就仅以StatusCode== http.StatusOK 作为接口成功调用的判断.
 另外有时间的话麻烦把godaddy 的参数模版发一份给我,我添加进前端模版里面?

**Comment by gdy666** [comment]
不急,我还没同步代码上github,这两天ddns部分重构优化的东西有点多,还没完成...

**Comment by snail2sky** [comment]
ok&nbsp; 第一次参与项目&nbsp; 😂，不规范的地方请严厉指出



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月7日(周日) 中午11:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gdy666/lucky] 挺好用的，但是有点小问题 (Issue #3)




 
不急,我还没同步代码上github,这两天ddns部分重构优化的东西有点多,还没完成...
