### ISSUE TITLE
设置了外网禁止访问后台，但还能从公网ip访问

### ISSUE THREAD

**Issue by ChanKamWo** [gdy666/lucky#31]
![](https://i.imgur.com/gndbyu5.png)

设置之后点过保存，重启，还是能从公网IP访问

**Comment by gdy666** [comment]
目前的内网IP的判断根据IP是否属于这几个网段
10.0.0.0/8
172.16.0.0/12
169.254.0.0/16
192.168.0.0/16，
如果外网开关关闭而你的访问IP不属于这个网段却又能访问的话，考虑一下你上层网络是否还使用了一层端口转发至lucky的访问端口。
另外1.6.0版本开始有安全入口设置，可以通过设置安全入口增加外网访问的安全性。

**Comment by ChanKamWo** [comment]
@gdy666 昨天安装过一次是可以禁止外网访问的，我后来卸载了又重装了一次。路由器的设置是有改过，但也没有开端口转发。

**Comment by gdy666** [comment]
那就猜不到哪里出了问题,下个版本得加上登录日志才行,记录登录IP,要不然不好排查这个问题了.

**Comment by gdy666** [comment]
v1.6.2版本加入了登录日志,有记录IP信息,有需要可更新测试.

**Comment by ChanKamWo** [comment]
更新了，确实是从内网地址登进去的。可能是OpenWRT哪里出了问题。

**Comment by gdy666** [comment]
> 更新了，确实是从内网地址登进去的。可能是OpenWRT哪里出了问题。

那就设置个安全入口吧,设置后访问后台就用 http://IP:端口/你设置的安全入口 
来访问后台,这样也起到一定安全作用.

**Comment by ChanKamWo** [comment]
可能是因为我始终是用LAN的设备访问，所以实际还是没有走WAN口。我用外网设备访问确实被禁止了。感谢作者快速回应！@gdy666
