### ISSUE TITLE
能否将自动生成配置文件直接写到/etc/lucky/目录里？

### ISSUE THREAD

**Issue by zxlhhyccc** [gdy666/lucky#32]
目前luci在启动时候：
1、init脚本只有创建/etc/lucky/目录才能将配置文件放入到该目录，而且在openwrt下软件启动时候openwrt的系统日志提示缺少配置文件，很难看！
2、目前v2raya软件在启动时自动生成配置文件到/etcv2raya/目录；
3、如果init脚本不创建/etc/lucky/目录，配置文件不知道在哪里（find查找不到，可能生成的配置文件无路径存放），登录客户端提示无配置文件不能保存！
![image](https://user-images.githubusercontent.com/45259624/202889110-82d8c217-d230-4bc0-b3ae-5bcd742d6cb4.png)

**Comment by gdy666** [comment]
好吧,这个原来是有的,是我对Openwrt理解不够删错了...我有叫sirpdboy大佬加回去,他可能太忙没有加.
你根据这个删除的commmit改改..
https://github.com/sirpdboy/luci-app-lucky/commit/3502eb0c6893ef1aac5809d214449c7a1b8e638a

**Comment by zxlhhyccc** [comment]
> 好吧,这个原来是有的,是我对Openwrt理解不够删错了...我有叫sirpdboy大佬加回去,他可能太忙没有加. 你根据这个删除的commmit改改.. [sirpdboy/luci-app-lucky@3502eb0](https://github.com/sirpdboy/luci-app-lucky/commit/3502eb0c6893ef1aac5809d214449c7a1b8e638a)

你说的是通过Makefile将默认配置编译进去，加上去是没有问题，但是lucky是会自动生成配置文件的，我的意思是比照v2raya由lucky在运行时自动新建/etc/lucky/目录并将生成的配置文件自动存储到/etc/lucky/目录。sirpdboy大佬删除的仅仅是init脚本中的代码。。。
另外，sirpdboy大佬luci的脚本貌似有点问题，如果通过ipk安装的话，软件会自动运行，我修改了一下，你帮忙看看可以么？如果可以我就pr到sirpdboy大佬仓库。
init脚本：
`````
#!/bin/sh /etc/rc.common
#
# Copyright (C) 2021-2022  sirpdboy  <herboy2008@gmail.com> https://github.com/sirpdboy/luci-app-lucky 
#
# This file is part of lucky .
# 
# This is free software, licensed under the Apache License, Version 2.0 .
#


START=99
USE_PROCD=1

PROG=/usr/bin/lucky
CONFDIR=/etc/lucky
CONF=/etc/lucky/lucky.conf
UCICONF=/etc/config/lucky

lucky_prepare() {
	pgrep -f /usr/bin/lucky | xargs kill -9 >/dev/null 2>&1 
	logger -t lucky -p warn "lucky is stop."
}

init_conf(){
	[ -d $CONFDIR ] || mkdir -p $CONFDIR 2>/dev/null
	# lucky自动生成配置文件，不需要提供默认配置
	# [ -s ${CONF}/lucky-default.conf ]  && cp -r $CONFDIR/lucky-default.conf $CONF || return 1
}

start_instance() {
	lucky_prepare
	if [ -s ${UCICONF} ];then  #存在uci配置文件，从uci配置读取端口
		local enabled
		config_get_bool enabled "$1" 'enabled' '0'
		[ "$enabled" = "1" ] || return 1

		local logger port
		config_get_bool logger "$1" 'logger' '1'
		config_get port "$1" 'port' '16601'

		[ -s ${CONF} ] || init_conf
		#sed -i "s/16601/$port/g" "$CONF" 端口可能会被用户修改，这个用不上
		logger -t lucky -p warn "lucky is start."
		echo "lucky is start."
		procd_open_instance
		procd_set_param command "$PROG" -c "$CONF" -p $port
		[ "x$logger" == x1 ] && procd_set_param stderr 1
		procd_set_param respawn
		procd_close_instance
	else #不存在UCI配置文件启动时就指定端口参数
		logger -t lucky -p warn "lucky is start."
		echo "lucky is start."
		procd_open_instance
		procd_set_param command "$PROG" -c "$CONF"
		[ "x$logger" == x1 ] && procd_set_param stderr 1
		procd_set_param respawn
		procd_close_instance
	fi
}

start_service() {
	config_load 'lucky'
	config_foreach start_instance 'lucky'
}

service_triggers() {
      procd_add_reload_trigger 'lucky'
}
````

**Comment by gdy666** [comment]
ipk安装软件会自动运行的问题是不是注释掉
luci-app-lucky/tree/main/lucky/files)/luci-lucky.uci-default 这个文件的第三第四行就好了?
openwrt相关的东西我不熟悉,你自己修改测试吧.

**Comment by zxlhhyccc** [comment]
> ipk安装软件会自动运行的问题是不是注释掉 luci-app-lucky/tree/main/lucky/files)/luci-lucky.uci-default 这个文件的第三第四行就好了? openwrt相关的东西我不熟悉,你自己修改测试吧.

删除了还是一样。。。

**Comment by gdy666** [comment]
按照我上面讲的删除那两行以后再把init脚本里面的
config_get_bool enabled $1 enabled 1
改为
config_get_bool enabled $1 enabled 0
不就可以了么?

**Comment by gdy666** [comment]
这里涉及到两个luci-app-lucky.ipk和lucky.ipk,
有强迫症的话细节自己慢慢调吧,
luck-app-lucky 问题直接找sirpdboy大佬吧,我这边只负责解决lucky软件功能bug,不再讨论openwrt相关问题.

**Comment by zxlhhyccc** [comment]
> 按照我上面讲的删除那两行以后再把init脚本里面的 config_get_bool enabled $1 enabled 1 改为 config_get_bool enabled $1 enabled 0 不就可以了么?

把1改成0没用的。。。这个早就试过了。。。

**Comment by zxlhhyccc** [comment]
> 这里涉及到两个luci-app-lucky.ipk和lucky.ipk, 有强迫症的话细节自己慢慢调吧, luck-app-lucky 问题直接找sirpdboy大佬吧,我这边只负责解决lucky软件功能bug,不再讨论openwrt相关问题.

我理解了sirpdboy大佬的意思了，在无uci配置文件时，软件自动运行，免去单独启动软件，而在有uci文件时，由luci-app进行控制。。。
另外，我把启动脚本也更新了，更符合标准规范的写法。。。

**Comment by gdy666** [comment]
https://github.com/gdy666/lucky/releases
1.6.2版本开始会同步发布多平台openwrt ipk安装包,
相关代码是我在sirpdboy大佬版本基础上上魔改的
https://github.com/gdy666/luci-app-lucky
