### ISSUE TITLE
为啥STUN穿透里，穿透类型只能单选？

### ISSUE THREAD

**Issue by wenpo1975** [gdy666/lucky#34]
![image](https://user-images.githubusercontent.com/24839804/207766581-cea22042-2450-468c-a9df-fb0d41506601.png)

如图，穿透类型 TCP/UDP只能二选一。
https://github.com/gdy666/luci-app-lucky/releases/tag/v1.7.4

**Comment by gdy666** [comment]
怎么说呢,即使让你一次选上两种类型,也保证不了同一端口的TCP/UDP得到的公网端口是同样的.

**Comment by gdy666** [comment]
受到STUN底层原理影响,我觉得用二选一方式是比较恰当的.
如果真的有需要就添加多条穿透规则,当然同一端口的两种类型得到的公网端口大概率是不一样.

**Comment by wenpo1975** [comment]
> 受到STUN底层原理影响,我觉得用二选一方式是比较恰当的. 如果真的有需要就添加多条穿透规则,当然同一端口的两种类型得到的公网端口大概率是不一样.

理解您说的；
不过BT软件，只能设置一个端口。添加两个转发的话，也只能有一个用得上。
