### ISSUE TITLE
一段时间后lucky服务会自动关闭，希望增加一个进程守护的功能

### ISSUE THREAD

**Issue by milkman-wang** [gdy666/lucky#36]
一段时间后lucky服务会自动关闭，希望增加一个进程守护的功能
已点star

**Comment by gdy666** [comment]
我运行在小米ax6000 官方路由系统上面一个月以上都没出现过关闭现象，你是通过什么方式安装的呢？运行在什么路由系统上？

**Comment by gdy666** [comment]
使用了哪些功能

**Comment by milkman-wang** [comment]
ax3600
只使用了端口转发
运行在openwrt上，内核5.15
github下载安装包安装的
一个星期内出现了两次这种情况
![833BB2CF-29CD-49FA-848F-2A1D8D161B0F](https://user-images.githubusercontent.com/109866905/208270996-336fa6ef-0b9e-4bc9-ae57-d873754c0f31.png)
![720DEB28-7887-4F28-8F6D-E4931743BA1D](https://user-images.githubusercontent.com/109866905/208270999-c3f043d7-8f3b-42ce-b23c-e324922e4fb4.png)

**Comment by gdy666** [comment]
猜测可能是UDP转发底层有BUG，我先想办法复现查一下。

**Comment by gdy666** [comment]
转发规则设置里面的UDP参数部分你是怎样设置的，截图我看看。

**Comment by milkman-wang** [comment]
![CB079C28-BE67-44CE-9E3F-060AC6572CE7](https://user-images.githubusercontent.com/109866905/208271454-327a4d74-662c-46ca-8f56-a598d9ea37b2.jpeg)
![71550EA8-F022-49D9-BF76-D47E2EC380AD](https://user-images.githubusercontent.com/109866905/208271455-a032ed69-03ee-4f4a-a13b-62f03a9ddfba.jpeg)
![37D6D53D-08E7-4B43-8AF0-23A9DCB46CC3](https://user-images.githubusercontent.com/109866905/208271456-4e27fbf5-c149-41d7-b100-38832a94dc49.jpeg)

**Comment by gdy666** [comment]
两次自动关闭是发生在使用moonlight过程中？

**Comment by milkman-wang** [comment]
一次是moonlight，一次是我昨天配置dsm的时候

**Comment by milkman-wang** [comment]
路由器重启了，看不到日志了。应该还会复现，到时我发上来

**Comment by gdy666** [comment]
好的，你先看看能不能捕获到异常日志，不行的话我发个debug版你试试。

**Comment by milkman-wang** [comment]
好的，你发我吧，我试试

**Comment by gdy666** [comment]
稍等，我先修改一下，让lucky尽量捕获崩溃日志而避免程序崩溃，并在后台设置增加一个开关让用户决定是否保存崩溃日志。
今天晚些时候再发布了。

**Comment by milkman-wang** [comment]
好，辛苦了

**Comment by gdy666** [comment]
先加下我QQ:272288813
