### ISSUE TITLE
反代遇到的问题

### ISSUE THREAD

**Issue by 3858809** [gdy666/lucky#40]
作者你好我是新手 遇到两个问题想咨询一下
问题一
在重启路由器的时候 貌似反代理服务全部都开不起来要手动开，日志里面都是 120.0.0.1:53 什么的，是因为路由器还没有初始化好数据吗

问题二
有时候手动开启也开不起来，有时候手动开启可以开启，有时候开不起来，开不起来的的报错内容如下：
Web服务规则 [op6]启用失败: 启用反向代理规则[www.xx.com:12345]出错:listen tcp6 [xxxx:xxxx:xxxx:xxxx::1]:12345: bind: cannot assign requested address
我简单的排查了一下发现日志报错力的ip地址和cf上解析的ip地址对不上好像一直是旧的，会不会是这个原因？如果是的话要如何解决，我一下子无从下手对openwrt不太熟
有时候ipv4也会出现上面的情况，我重启路由器之后，ipv4就可以正常解析到最新的ip了，同时反代理开启也不会报错了；
可是ipv6的我怎么重启都没有用不知道为什么。

我使用的是硬件是 树莓派4b做主路由
使用openwrt中的docker 安装的你的luxky。
使用：docker run -d --name lucky --restart=always --net=host gdy666/lucky。该命令安装
ipv6网络正常可以使用，我端口转发的情况ipv6我正常可以使用
但是我想使用反代以https的方式在外网访问

以上是全部非常感谢🙏

**Comment by gdy666** [comment]
1.Web服务规则监听地址不要填写，直接留空。
2.DDNS问题请在DDNS规则列表截图，以及截那个同步出错的错误日志明细。
