### ISSUE TITLE
红米AX6000编译成功但运行报错Segmentation fault

### ISSUE THREAD

**Issue by JAM2199562** [gdy666/lucky#41]
大吉太有用了，必须点个star，现在遇到一个问题自己不会弄

![image](https://user-images.githubusercontent.com/10511667/212377025-096a2459-1ca3-49c7-a0ef-8c310455b17b.png)

路由器是红米AX6000，编译使用的https://github.com/hanwckf/immortalwrt-mt798x
报错如上图，我大致查了一下，编译的时候访问的下载链接是
github.com/gdy666/lucky/releases/download/v1.7.5/lucky_1.7.5_**Linux**_arm64.tar.gz
但是您发布的ipk文件却是lucky_1.7.5_**Openwrt**_arm64.tar.gz，不知道能否解决。

**Comment by gdy666** [comment]
编译下载的不是ipk,是那个tag.gz没问题的。至于运行为什么会出现这个错误就不是很清楚了。。。

**Comment by JAM2199562** [comment]
往files文件夹里面丢了个二进制，问题也算是解决了，谢谢啦
