### ISSUE TITLE
希望 SSL 证书能直接设置文件路径

### ISSUE THREAD

**Issue by sanfang0766** [gdy666/lucky#42]
我路由本身就配置了 ssl 证书，希望能直接选择路由本身的证书。

**Comment by gdy666** [comment]
v6那边的目标端口是什么服务的？另外你发送数据包后的日志肯定有显示，提供一下，不然根本没法分析

**Comment by tsiens** [comment]
+1,我是群晖设置了定时任务三个月自动刷新证书，目前可以设置群晖自动推送到路由器上，希望lucky能自动使用路由器某路径下的证书，这样就不用定时去lucky网页上传证书了 @gdy666

**Comment by tsiens** [comment]
或者说lucky能直接集成[syno-acme](https://github.com/andyzhshg/syno-acme)就更完美了

**Comment by tsiens** [comment]
> > 
> 
> ![QQ截图20230322182909](https://user-images.githubusercontent.com/2849711/226875826-f221bc90-162b-4aa3-8c68-1448d0978f67.png) 近期会完成，ACME只支持cloudflare，阿里，腾讯。

期待，那就完美了

**Comment by gdy666** [comment]
1.9.1版本已发布。
