### ISSUE TITLE
提问:一个穿透规则能不能搞俩webhook

### ISSUE THREAD

**Issue by cancundeyingzi** [gdy666/lucky#44]
一个本地webhook server后端工作,另一个类似server酱提示

**Comment by gdy666** [comment]
有机会增加一个stun全局webhook,任意一条规则都可以触发的webhook.

**Comment by cancundeyingzi** [comment]
(已通过后端转发post/get解决问题)

**Comment by gdy666** [comment]
v1.7.21已加入stun全局webhook.
