### ISSUE TITLE
[功能请求]   STUN IPv4内网穿透 增加 NAT-PMP 功能支持 以支持自动端口映射

### ISSUE THREAD

**Issue by rankaiyx** [gdy666/lucky#45]
STUN IPv4内网穿透  增加 NAT-PMP 功能支持  以支持自动端口映射

当NAT-PMP客户端（如pt软件）向NAT-PMP服务端（网关）请求映射端口时，返回最外层的实际的外部端口和IP

参考资料
协议文档
https://www.rfc-editor.org/rfc/rfc6886.html
"Correspondingly, NAT-PMP allows a client to request a desired external port, and if that external port is already in use by some other client, the NAT-PMP server will instead assign some other available external port. UPnP IGD does not do this. "
”相应地，NAT-PMP允许客户端请求所需的外部端口，并且如果该外部端口已经被某个其他客户端使用，则NAT-PMP服务器将改为分配某个其他可用外部端口。UPnP IGD不执行此操作。“

NAT-PMP协议里，这里给了自由操作端口的空间。

这是一个 python的NAT-PMP服务端实现，可以借鉴：
https://github.com/agubelu/NATPMP-Suite

**Comment by gdy666** [comment]
v1.8.3版本已增加stun natmap支持。
