### ISSUE TITLE
MQTT协议建议新增忽略证书错误选项（目前巴法云的证书过期了

### ISSUE THREAD

**Issue by bwenquan** [gdy666/lucky#46]
在测试链接的时候发现：
![image](https://user-images.githubusercontent.com/41329948/219036987-1eef0436-7a09-4607-a446-28daff05c35a.png)
看了下代码，连接的是
![image](https://user-images.githubusercontent.com/41329948/219037098-c29913c7-656a-4396-a8f4-c5efaa229d1d.png)
带进浏览器访问，证书确实过期
![image](https://user-images.githubusercontent.com/41329948/219037198-6c4dcee0-07f6-4ad7-bcc8-7567424e8152.png)

**Comment by gdy666** [comment]
你在lucky的设置页面--全局设置里面打开“跳过证书验证”开关，然后重启一下lucky。

**Comment by bwenquan** [comment]
已解决~
设置 - 全局设置 - (TLS)跳过证书验证 打开就行啊
