### ISSUE TITLE
stun内网穿透调用webhook时获取不到正确的ipAddr变量

### ISSUE THREAD

**Issue by dy2898** [gdy666/lucky#47]
内网穿透调用webhook时获取不到正确的ipAddr变量，ipAddr总是一个固定的私网地址192.168.31.1:6666  
动态域名调用webhook的地址变量ipAddr也是错误的66.66.66.66

**Comment by gdy666** [comment]
你是通过webhook测试触发的吧？那是正常的。提交保存后才能获取真实信息。
