### ISSUE TITLE
关于lucky内存占用的问题

### ISSUE THREAD

**Issue by gzylg** [gdy666/lucky#48]
![image](https://user-images.githubusercontent.com/40072122/220772081-4af73ba3-bae4-4a55-acd8-62bfa23ec6db.png)

![image](https://user-images.githubusercontent.com/40072122/220772145-a088f23a-8156-4932-9f63-2fee256c90e3.png)

作者你好，首先先感谢你的应用，非常好用！

我有点疑问咨询一下，以上是对lucky内存占用的截图，我发现内存占用挺高的700多兆。

我的运行环境：i5 7500t，openwrt x86，分配了2G内存，lucky版本是最新的1.7.21，手动ipk安装。

配置了5个ipv4端口转发，1个ipv4动态域名，其他的功能全部没有使用，并且能关掉的都关了，700多兆的内存占用这是正常的么？

**Comment by gdy666** [comment]
VSZ不代表内存占用，忽略即可。具体内存占用参考lucky的总览页面。
