### ISSUE TITLE
请问ipv6端口转发地址改变如何解决

### ISSUE THREAD

**Issue by huangwj55** [gdy666/lucky#49]
我用的openwrt，能够正常使用端口转发与ddns，问题在于路由器重启后获取到的ipv6地址改了，导致端口转发失败，但ddns仍正常运行，可以同步，请问有什么解决方法吗？

**Comment by huangwj55** [comment]
作为初学者我研究了一下搞了个脚本自动更新配置
#！ /bin/bash
nowip6=$(ip addr show br-lan | grep 'inet6' -m 1 | sed 's/^.*inet6 //g' |sed 's#/64.*$##g')
sed -i "s/^.*ListenAddress.*$/\"ListenAddress\":\"$nowip6\"/" /etc/config/lucky.daji/lucky.conf
测试了一下连接没问题，丢到crontab里不管了

**Comment by gdy666** [comment]
不是提示了么，没特殊需求的话监听地址留空就行了啊

**Comment by riskingl** [comment]
谢谢大佬辛苦制作，正在梅林固件使用中。
