### ISSUE TITLE
管理后台菜单可以直接显示，不用折叠

### ISSUE THREAD

**Issue by YanYeek** [gdy666/lucky#51]
![image](https://user-images.githubusercontent.com/48875922/225500277-0588e0c9-f6a9-4d24-aa77-b6179bc8efc3.png)
每次我登陆完去找穿透规则列表点击都不方便

**Comment by gdy666** [comment]
1.8.5版本已经优化菜单显示，请升级。

**Comment by YanYeek** [comment]
> 

大佬牛逼
