### ISSUE TITLE
关于端口转发

### ISSUE THREAD

**Issue by goodyouh** [gdy666/lucky#52]
在端口转发的规则里，我可以设置监听的协议是ipv4，而目标协议是ipv6吗？

我进行了这样的设置，监听地址是我本机（使用ipv4），目标地址是一台我可以ping通得ipv6的地址

在使用时，网页显示：已接受有数据，已发送没有数据

**Comment by gdy666** [comment]
看编辑按钮左边的日志显示什么

**Comment by goodyouh** [comment]
{"ExtInfo":{},"level":"warning","msg":" firewall.EnablePort Warn:ip6tables not found"}
从 Windows 版邮件发送

发件人: 古大羊
发送时间: 2023年3月17日 21:49
收件人: gdy666/lucky
抄送: goodyouh; Author
主题: Re: [gdy666/lucky] 关于端口转发 (Issue #52)

看编辑按钮左边的日志显示什么

**Comment by gdy666** [comment]
这条不影响使用

**Comment by goodyouh** [comment]
我往监听的端口发送包，然后用wireshark抓包，如图：


有一个被成功转发，而另一个显示不可达。

我想了解进行了端口转发后，目的端口往回发信息，会逆着端口转发，发回到与监听端口联系的端口吗

还有就是已发送没数据，已发送代表什么


从 Windows 版邮件发送

发件人: 古大羊
发送时间: 2023年3月18日 22:31
收件人: gdy666/lucky
抄送: goodyouh; Author
主题: Re: [gdy666/lucky] 关于端口转发 (Issue #52)

这条不影响使用

**Comment by goodyouh** [comment]
我是用这个软件的目的是为了利用ipv6与朋友玩局域网（ipv4）游戏（不在一个局域网下）

　　局域网游戏会有一个房主的端口，在帝国时代中是2299，加入房间可以填写ip，便会向ip：2299发送信息。
　　我打算加入房间是填写127.0.0.1，使用端口转发，将这条信息使用ipv6，发往房主电脑的7980端口。在房主电脑上也使用端口转发，将这条信息转发到他的2299（ipv4）端口，也就是他的游戏房主端口。
　　您说这样的设计可以实现吗？
　　 

从 Windows 版邮件发送

发件人: 古大羊
发送时间: 2023年3月18日 22:31
收件人: gdy666/lucky
抄送: goodyouh; Author
主题: Re: [gdy666/lucky] 关于端口转发 (Issue #52)

这条不影响使用

**Comment by gdy666** [comment]
不了解帝国游戏实际的通信方式，还是组异地虚拟局域网靠谱一些。openvpn或者zerotier。openvpn可以用lucky转发
