### ISSUE TITLE
证书文件和 key 文件名不一样提示域前后证书域名不一致

### ISSUE THREAD

**Issue by sanfang0766** [gdy666/lucky#54]
因为我是用 fullchain.cer 同步到 OpenWRT 的，然后用路径设置 SSL 时候就会提示前后证书域名不一致...
我偷懒，ACME.SH 文件夹里面是 fullchain.cer，我直接同步不改名。

![屏幕截图 2023-03-27 095101](https://user-images.githubusercontent.com/81353624/227822312-14842534-323a-414a-9c05-08aa2f676481.png)

**Comment by gdy666** [comment]
应该是crt不是cer吧？

**Comment by sanfang0766** [comment]
> 应该是crt不是cer吧？

acme.sh 自动生成的，确定是 fullchain.cer
因为 .csr 是没有中间证书的我就用 fullchain.cer ...

**Comment by gdy666** [comment]
我看了下代码，有个bug，判断有误，晚点再修复

**Comment by gdy666** [comment]
已发布修复版，你试试。
