### ISSUE TITLE
lucky不能更新cloudflare的动态域名?

### ISSUE THREAD

**Issue by 725216** [gdy666/lucky#55]
搜了一下,说是cloudflare不支持freenom的免费域名?
![Uploading 1.jpg…]()
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()

**Comment by 725216** [comment]
dnspod和dynv6正常使用
![1](https://user-images.githubusercontent.com/22210790/227884702-4b359716-fc81-4fad-91fd-f8827ffc9f96.jpg)
![2](https://user-images.githubusercontent.com/22210790/227884755-34ab103a-b549-4764-9d56-a71051d2e67a.jpg)
![3](https://user-images.githubusercontent.com/22210790/227884806-850cfd00-ba77-4e98-9c1a-b53275fb24c3.jpg)

**Comment by gdy666** [comment]
你得问cloudflare，不是问我的。。。
