### ISSUE TITLE
LEDE每次更新后应用和配置均丢失

### ISSUE THREAD

**Issue by 1014982466** [gdy666/lucky#57]
使用了一键安装，安装方式时选择了在/etc目录下安装(适合root用户)
Lede更新时勾选保留配置（小更新，不是跨内核版本的大更新）
更新后需要重新安装，且需要重新配置
能否在编译时加入Lede，或者有什么办法能在更新后尽可能保留下程序本体和配置？

**Comment by gdy666** [comment]
lucky后台设置最下方可以备份还原配置。
openwrt可以尝试使用ipk包方式安装。
https://github.com/gdy666/luci-app-lucky
ipk安装前记得要先执行多一次一键脚本卸载原来的版本。
