### ISSUE TITLE
根据DUID给内网已通过DHCPV6分配地址的IPV6终端实现DDNS

### ISSUE THREAD

**Issue by gzxiexl** [gdy666/lucky#61]
https://github.com/Wing-Siu/Openwrt-IPv6-DDNS-Script

希望大佬能够集成

**Comment by gdy666** [comment]
这个完全没用增加的必要。你把HostDUID替换一下，然后填进DDNS的自定义脚本不就是了么
cat /tmp/hosts/odhcpd | grep HostDUID | awk -F " " '{print $NF}' | sed 's/\/128//g'
