### ISSUE TITLE
改善STUN穿透功能的使用建议

### ISSUE THREAD

**Issue by ilolita945** [gdy666/lucky#62]
目前穿透服务器列表为单一设置，能否增加一个统一设置选项，以及新增一个自动刷新STUN服务器列表功能（项目地址：https://github.com/pradt2/always-online-stun）

**Comment by gdy666** [comment]
没必要，并且很多都不支持TCP穿透的，不考虑增加此功能。

**Comment by ilolita945** [comment]
> 没必要，并且很多都不支持TCP穿透的，不考虑增加此功能。

添加一个统一配置STUN服务器列表的可好，Lucky内置的STUN穿透功能非常好用

**Comment by ilolita945** [comment]
> 没必要，并且很多都不支持TCP穿透的，不考虑增加此功能。

一个端口一个列表  个人维护起来比较麻烦，可否考虑下..

**Comment by gdy666** [comment]
默认内置的STUN列表已经足够，根本不需要维护。

**Comment by gdy666** [comment]
后续有时间再考虑增加完善STUN功能的问题，最近比较忙就先不加了。

**Comment by ilolita945** [comment]
> 

感谢

**Comment by gdy666** [comment]
2.0.1版本已增加stun全局服务器列表设置.有需要访问网盘下载更新。

**Comment by ilolita945** [comment]
> 2.0.1版本已增加stun全局服务器列表设置.有需要访问网盘下载更新。

拜谢大佬重视
