### ISSUE TITLE
Webhook添加新方法PATCH

### ISSUE THREAD

**Issue by IMZCC** [gdy666/lucky#63]
想更新cloudflare redirect rule与github gist其中更新api都是PATCH类型的

Github Gist RestApi:https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28#update-a-gist

**Comment by gdy666** [comment]
OK，下个版本加上

**Comment by gdy666** [comment]
https://url21.ctfile.com/d/44547821-55537427-a5525e?p=16601 
新版先放网盘了，你试试
