### ISSUE TITLE
使用端口转发可以正常访问，Web服务反向代理[400: Bad Request]

### ISSUE THREAD

**Issue by xjpz** [gdy666/lucky#64]
Docker 部署，使用端口转发可以正常访问，关闭端口转发 开启Web服务反向代理出现[400: Bad Request]，web服务规则里日志显示正常没有发现报错

**Comment by gdy666** [comment]
1.换端口。
2.附上配置截图和访问日志截图。

**Comment by xjpz** [comment]
规则日志

![1681985523417](https://user-images.githubusercontent.com/10084510/233337591-8ddc5f14-f6bb-4f91-a874-bbf09438ed86.jpg)

web服务总日志

![1681985523418](https://user-images.githubusercontent.com/10084510/233337796-782587f2-5885-4f2e-92a1-2850e414a487.png)

web服务规则

![1681985626517](https://user-images.githubusercontent.com/10084510/233339065-e93fbe75-8f8e-42be-83fb-12b45613ce94.jpg)

**Comment by gdy666** [comment]
看日志没发现异常，后端地址是什么服务的

**Comment by xjpz** [comment]
HomeAssistant

**Comment by gdy666** [comment]
HomeAssistant 反向代理要设置白名单，自己搜索一下就知道了。

**Comment by xjpz** [comment]
多谢，已通过HomeAssistant配置白名单解决
