### ISSUE TITLE
咨询两个问题

### ISSUE THREAD

**Issue by wangx2** [gdy666/lucky#65]
环境docker host模式
1、就是DDNS无法自动更新，怎么点都没用，日志也不显示
![image](https://user-images.githubusercontent.com/16116338/233528560-a9ddb64f-83aa-450d-a084-f78037be22c7.png)
2、就是我使用内网穿透功能，穿透到是成功了，但是mstsc无法连接，提示如下
![image](https://user-images.githubusercontent.com/16116338/233528675-6e235e46-1b23-4980-af93-e838c09ef12d.png)
有的时候就又可以连接，不清楚是什么原因造成的，可以解决吗？

**Comment by gdy666** [comment]
1.第一个问题,docker环境尽量使用接口方式获取IP。
2.第二问题无解。

**Comment by wangx2** [comment]
> 

麻烦再给看看DDNS是不是那里没有设置对？
![image](https://user-images.githubusercontent.com/16116338/233543913-40bd92e6-3be3-47ec-899d-d45850752811.png)
![image](https://user-images.githubusercontent.com/16116338/233544036-e0f2483e-794e-4689-8d5e-7a106393dd76.png)
![image](https://user-images.githubusercontent.com/16116338/233544122-c5e0190a-084c-4682-b851-2de9efa98dc6.png)

**Comment by wangx2** [comment]
不知道什么原因，我使用DDNS-GO是正常的

**Comment by gdy666** [comment]
动态域名模块我重构了一下，这两天发布了再试试

**Comment by gdy666** [comment]
https://url21.ctfile.com/d/44547821-55537427-a5525e?p=16601 
新版先放网盘了，你试试

**Comment by wangx2** [comment]
> https://url21.ctfile.com/d/44547821-55537427-a5525e?p=16601 新版先放网盘了，你试试

可以啦，秒推送
