### ISSUE TITLE
请教下：能支持外网转外网吗？

### ISSUE THREAD

**Issue by idragonet** [gdy666/lucky#66]
* K3路由器刷openwrt，有公网IP，域名vps1.my.com做了DDNS。

* 需求：把路由器的9000端口做TCP/UDP转发到Oracle VPS：168.138.1.1:443上，其他外网设备访问：vps1.my.com:9000 转发到：Oracle VPS：168.138.1.1:443
 也就是：等于路由器做中转机，因为公司电信出海太慢，家里联通快.

**Comment by gdy666** [comment]
可以，端口转发目标地址支持填写域名或者外网IP

**Comment by idragonet** [comment]
> 

谢谢大佬，太好了！周末回去试试。
