### ISSUE TITLE
修改腾讯云创建密钥的地址

### ISSUE THREAD

**Issue by AllenPu2020** [gdy666/lucky#67]
版本：你的 Lucky.大吉   当前版本：1.10.8 linux(x86_64)
运行环境：docker

现有的 *创建密钥* 超链接是这个
https://console.dnspod.cn/account/token

应该修改成这个
https://console.dnspod.cn/account/token/token

因为腾讯云默认进去是 [腾讯云 API 密钥](https://console.dnspod.cn/account/token/apikey)
我们需要的是 [DNSPod Token](https://console.dnspod.cn/account/token/token)

**Comment by gdy666** [comment]
OK,我改改
