### ISSUE TITLE
反向代理导致https无法跟随

### ISSUE THREAD

**Issue by zhx47** [gdy666/lucky#68]
这个场景经常遇到，因为外部暴露为https而后端为http，反向代理后导致原始协议丢失，后端读取协议头的时候是http。
这个在slb nginx中也很常见，也是通过新增头来标明，是否可以添加此功能。

定制规则中提供了IP的头，是否可以新增协议跟随的头
![image](https://user-images.githubusercontent.com/61264955/236621782-2fd80c8e-82ea-4c89-bac6-1d96b5ba1911.png)

像X-Real-Proto, X-Forwarded-Proto这种头也应该开放选项进行附加

**Comment by gdy666** [comment]
2.0.1版本已增加追加客户端协议头到指定Header开关

**Comment by zhx47** [comment]
> 2.0.1版本已增加追加客户端协议头到指定Header开关

辛苦了
