### ISSUE TITLE
預設要繞過生成16601啊，也咩爹

### ISSUE THREAD

**Issue by YheonYeung** [gdy666/lucky#69]
![image](https://user-images.githubusercontent.com/63342274/236686526-b6a5518e-42f8-438a-9919-78f2e10f51ff.png)
搞個16601出來，BC直接拒絕
![image](https://user-images.githubusercontent.com/63342274/236686603-c56409af-a88d-4f72-a0aa-f9c5a115e780.png)

**Comment by gdy666** [comment]
看不懂这个穿透获得的公网端口和lucky端口一样的话会有什么影响

**Comment by YheonYeung** [comment]
lucky.exe獲得16601，添加到BitComet黃臉阻塞，我是要關掉exe添加？

**Comment by gdy666** [comment]
stun穿透问题看文档看教程，任何相关问题请自行研究

**Comment by gdy666** [comment]
lucky和BitComet不要运行在同一机子就能完全避免这种情况。不可能为了这一小概率特殊情况去增加措施避开端口的。

**Comment by YheonYeung** [comment]
將「穿透通道监听端口」填0，生出來的填到路由器的轉發變成要填兩個，而且填到BC完全不通。
我還不如老方法固定22223，每次只要填生成的就好。
當然，如果有固定生成的方法也請教一下。
