### ISSUE TITLE
访问后台提示错误

### ISSUE THREAD

**Issue by scdlyh** [gdy666/lucky#7]
使用一键脚本完成安装，并提示lucky已成功运行。

访问后台http://ip:16601/时提示
{"msg":"Forbidden Internetaccess ","ret":1}

运行系统为 Debian 11 x64

**Comment by gdy666** [comment]
你是通过外网IP地址还是内网IP地址访问的呢?默认是禁止外网IP访问的,需要在设置页面打开允许外网访问.如果是通过内网IP访问可能是是程序的内网网段判断有问题,请提供一下你现在的IP网段我看看.

**Comment by scdlyh** [comment]
>感谢回复，问题已解决，确实是使用了外网访问引起的，配置文件中设置 "AllowInternetaccess": false, 后看到登录界面了
