### ISSUE TITLE
关于反向代理unraid 无法访问

### ISSUE THREAD

**Issue by joker-nan** [gdy666/lucky#70]
这是一个很好的项目，我使用的时openwrt固件内置的lucky   在反代unraid 的时候 用【https://域名】访问会跳转到http  提示服务器拒绝访问  会跳转到【http://域名/Dashboard】这样子  我测试了 如果直接用【https://域名/login】访问就可以登陆到unraid 的登陆页面   不知道问题出在哪里

**Comment by joker-nan** [comment]
我遇到了一个感知上的问题  在访问反代域名的时候网页的响应时间感觉有点长需要四到五秒才能把网站打开     不知道时我配置的问题   还是我的设备配置不够高引起的

**Comment by joker-nan** [comment]
![image](https://github.com/gdy666/lucky/assets/50975193/5e5f1b0e-92f4-4b33-ba09-e88f921902ca)
这个是访问域名的响应时间，等待反代服务器响应的时间就花三秒多  
![image](https://github.com/gdy666/lucky/assets/50975193/1e1c6acd-afac-4711-95df-ef262278f133)
这是我正常访问百度响应时间，我的感觉像是服务器得到请求  它先去往内网的服务拿到所需要的资源，整理好各个方面的资源然后才去响应请求，所以造成请求时间过长

**Comment by gdy666** [comment]
抱歉，不懂

**Comment by joker-nan** [comment]
谢谢，我自己研究一下。再次感谢分享如此好用的项目
