### ISSUE TITLE
程序进程怎么关闭

### ISSUE THREAD

**Issue by tnnevol** [gdy666/lucky#71]
未发现该服务的进程关闭命令，并且kill后还会自启动，最后看到该进程的ppid 为1，很容易变成僵尸进程,麻烦作者提供一个关闭服务的命令

**Comment by gdy666** [comment]
lucky就是一个普通的程序，不存在所谓杀不死的情况，你用什么版本的lucky?docker版?

**Comment by tnnevol** [comment]
> lucky就是一个普通的程序，不存在所谓杀不死的情况，你用什么版本的lucky?docker版?

我是在ubuntu上跑的，我发现kill进程后，一会儿时间就会自启动，最后查找到该进程的守护进程id 号变成了1，无法正常关闭进程。

**Comment by gdy666** [comment]
查一下cron任务列表是不是有lucky的定时检测保护

**Comment by tnnevol** [comment]
> 查一下cron任务列表是不是有lucky的定时检测保护

确实查看到了，麻烦还是在 lucky 上加一个关闭服务的快捷指令吧，确实挺难找到这个任务

**Comment by gdy666** [comment]
不需要lucky的话执行多一次安装指令选择2把lucky卸载就可以了。
系统太多，没精力适配，有需求的话看文档了解启动参数自己设置开机启动，手动控制lucky启动关闭就行了。
