### ISSUE TITLE
下载ssl证书是空文件夹

### ISSUE THREAD

**Issue by shimingliangsml** [gdy666/lucky#74]
你好，请问一下，下载ssl证书是空文件夹是正常的吗，想给后端配置ssl证书

**Comment by gdy666** [comment]
acme申请到了证书没？不应该是空文件的

**Comment by shimingliangsml** [comment]
[image: msedge_8neE45WLBM.png]
我这是已经申请到了吧，反代访问也显示https正常，我是在openwrt上直接安装使用的

古大羊 ***@***.***> 于2023年6月17日周六 11:02写道：

**Comment by gdy666** [comment]
看不到图片

**Comment by shimingliangsml** [comment]
![msedge_8neE45WLBM](https://github.com/gdy666/lucky/assets/58036024/f45a9974-5d03-4fb4-8e40-ab3b586625fb)

**Comment by shimingliangsml** [comment]
我是在pve下虚拟op做旁路由，使用的一键脚本安装，lucky版本，
我可以直接安装ipk版本试试看，不卸载现有的版本吗

**Comment by gdy666** [comment]
下载得到的是zip文件，里面不是有两个文件？怎么可能是空的

**Comment by gdy666** [comment]
解压出来，有些后端不支持crt格式的话你就把crt改为pem

**Comment by shimingliangsml** [comment]
我习惯性直接点开了，win11资源管理器不显示，
我直接解压出来就有了，不好意思打扰了，谢谢
