### ISSUE TITLE
SSL证书模块一个小功能需求。

### ISSUE THREAD

**Issue by a18ccms** [gdy666/lucky#75]
SSL证书那里，有个小需求，就是希望能有实际证书的地址。例如在日志中显示一个生成地址啥的。或者有个固定位置的实际文件。
现在证书密钥是存在配置文件里面，WEB下载的是实时生成。
这个需求的用途是可以把一个固定的证书路径和固定的文件名，共享给其它应用使用，写入它们的配置文件中。
例如ocserv，要不每三个月得重新下载上传一次证书，好麻烦。

**Comment by gdy666** [comment]
lucky设置页面打开 "开发者设置"开关，保存设置，比如token=AAAAAA
把你在web下载实时生成的那个地址中的Authorization部分替换为openToken，比如

http://192.168.31.1:16601/api/ssl/download?Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiZ2R5IiwiZXhwIjoxNjg3MzE2NDQ2LCJsb2dpbmtleSI6IlFlclk3NmFqcFduTmxiQkkiLCJwYXNzd29yZCI6IjY2ODI4MjExIn0.YWo-Qu6c_OMqhxQhdsuJAJH41dExOgS0mhInRqHLIlk&key=hY34Rxz84CdvEJKV&_=1687230061000
改成了
http://192.168.31.1:16601/api/ssl/download?openToken=AAAAAA&key=hY34Rxz84CdvEJKV&_=1687230061000

这种就是固定地址了

**Comment by a18ccms** [comment]
我说的固定地址是物理地址，/root/cert/cert.pem 类似这样。局域网内部开个nfs，就可以挂在到系统里，或者直接挂载到其它容器里就很方便。不是固定的下载地址，下载地址还是不固定的好。

**Comment by gdy666** [comment]
好吧。。。有空再加上

**Comment by gdy666** [comment]
网盘下载v2.1.3版本试试

**Comment by a18ccms** [comment]
我是OpenWrt版本。网盘里还没更新OP。

**Comment by gdy666** [comment]
直接在lucky后台上传对应平台的tar.gz包升级就行了

**Comment by a18ccms** [comment]
升级到2.1.3了。看到证书映射了。得等晚上试试了。。555
555,我原来是1.10.8 想先升级到2.0.1 再后台上传gz包。能保证兼容性。之后发现启动不了，觉得可能是因为没删除直接升级导致的。。九opkg移除软件了。。发现配置文件也移除了。。哈哈。。555。晚上重新配置吧。。

**Comment by a18ccms** [comment]
配置起来还挺快，哈哈，映射功能挺好用的。应该很完美。感谢~~ 大拇指!
