### ISSUE TITLE
SSL等待时间延长

### ISSUE THREAD

**Issue by tsiens** [gdy666/lucky#77]
目前是等待一分钟，然后查询不到增加的dns记录就出现
![image](https://github.com/gdy666/lucky/assets/24999801/33fa3802-2aa1-468c-90eb-6714ed237945)
之前用的acme.sh是等待五分钟的，一分钟确实dns还刷新不过来呢

**Comment by gdy666** [comment]
下个版本证书申请速度有明显改善，到时你再试试

**Comment by gdy666** [comment]
2.0.1版本已上传到网盘，有需要可以更新测试一下
