### ISSUE TITLE
反代可道云，能添加规则吗

### ISSUE THREAD

**Issue by AWSOMEALEX** [gdy666/lucky#78]
之前用NPM,需要在设置高级那里规则一些规则才可反代可道云，请问LUCKY有添加窗口吗？找了一圈没找着……

**Comment by gdy666** [comment]
![QQ截图20230706100726](https://github.com/gdy666/lucky/assets/2849711/4894b30b-ced6-41a9-bf31-63540ea66acc)
网盘更新2.0.1版本，定制模式开关这个开关，填入X-Forwarded-Proto就可以反代可道云。

**Comment by AWSOMEALEX** [comment]
谢谢大佬，到家试试！
