### ISSUE TITLE
不支持局域网的某一个端口转发到外网的同一个端口，比如说我有一个局域网的ip为192.168.31.18这个5555端口没办法直接转发到公网的5555端口，只能是非5555端口

### ISSUE THREAD

**Issue by wakaka123wakaka** [gdy666/lucky#79]

**Comment by gdy666** [comment]
除非端口冲突，否则不可能存在你所讲的情况。如果lucky所在系统的5555端口已经被其他程序占用，那么才会出现这种情况。

**Comment by wakaka123wakaka** [comment]
确实是因为拨号路由器运行的这个就是5000端口占导致端口冲突了，但是这种情况下，我想直接把5000端口映射到外部的5000端口进行访问，但是我似乎没有看到配置的地方

**Comment by gdy666** [comment]
你的udpxy占用了5000端口

**Comment by wakaka123wakaka** [comment]
但是我是局域网的运行服务占用5000端口，我想把他映射到公网的5000端口，这个就没办法实现了
