### ISSUE TITLE
功能需求😊

### ISSUE THREAD

**Issue by scdlyh** [gdy666/lucky#8]
希望能增加一个转发到域名的功能，域名支持解析到IPV6.
使用场景，lucky程序运行在支持 IPv6和 IPv4 公网的服务器上，在没有IPV6的情况下，通过IPv4地址访问服务器，服务器转发IPv4的流量到IPV6 _的远程地址中，实现代理访问没有公网IPV4的设备，同时访问者又处于IPV4网络中的情况

![](https://fastly.jsdelivr.net/gh/filess/img9@main/2022/09/07/1662520321025-a81b3fc9-1f1b-4748-ae92-83d17e240b1f.png)

**Comment by gdy666** [comment]
![QQ截图20220907150124](https://user-images.githubusercontent.com/2849711/188811056-1987393d-1eb9-47aa-b722-165bea32aa00.png)
你可以尝试一下这样设置,开启均衡负载,目标地址用域名+端口,填写两行相同的.
看看这样能不能达到你想要的功能.

**Comment by scdlyh** [comment]
> ![QQ截图20220907150124](https://user-images.githubusercontent.com/2849711/188811056-1987393d-1eb9-47aa-b722-165bea32aa00.png) 你可以尝试一下这样设置,开启均衡负载,目标地址用域名+端口,填写两行相同的. 看看这样能不能达到你想要的功能.

哈，居然还可以这样设置，现在按你的设置完美解决了我的需求，非常感谢
