### ISSUE TITLE
[问题]申请Cloudflare免费证书的时候出现问题

### ISSUE THREAD

**Issue by EdisonCh4n** [gdy666/lucky#85]
环境：群晖DOCKER host网络模式
有三个域名：两个托管在cloudflare上，一个托管在dnspod上，分别申请cloudflare上的一个域名和dnspod上的域名证书均无问题。
前两个域名均可正常反代解析访问
申请第二个cloudflare证书时出现以下提示：
（XXX为我的网站，已确定cloudflare的API是DNS的模板API，并为该域名的单独API）

023/08/18 02:43:27 [INFO] [XXX] acme: Obtaining bundled SAN certificate
2023/08/18 02:43:28 [INFO] [XXX] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/255864100386
2023/08/18 02:43:28 [INFO] [XXX] acme: use dns-01 solver
2023/08/18 02:43:28 [INFO] [XXX] acme: Preparing to solve DNS-01
2023/08/18 02:43:30 [INFO] [XXX] acme: Trying to solve DNS-01
2023/08/18 02:43:30 [INFO] [XXX] acme: Checking DNS record propagation using [114.114.114.114:53 208.67.222.222:443 119.29.29.29:53 176.103.130.131:5353 202.141.162.123:53 223.5.5.5:53 119.28.28.28:53]
2023/08/18 02:43:32 [INFO] Wait for propagation [timeout: 3m0s, interval: 2s]
2023/08/18 02:43:32 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:34 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:36 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:38 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:40 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:42 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:44 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:46 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:48 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:50 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:52 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:54 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:56 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:43:58 [INFO] [XXX] acme: Waiting for DNS record propagation.
2023/08/18 02:44:00 [INFO] [XXX] acme: Waiting for DNS record propagation.

**Comment by gdy666** [comment]
提供的日志不完整
