### ISSUE TITLE
op安装的问题

### ISSUE THREAD

**Issue by yishion819** [gdy666/lucky#9]
已经显示，安装成功并且运行起了，但忘记看完你的帖子了……“启动时请指定配置文件存放位置运行,要不然不会保存配置信息”，这一步看掉了，导致重启了软路由无法用ipv6远程连接了，请问这一步在op下面如何操作，恳求大佬指点一下，跪谢了

**Comment by yishion819** [comment]
看到仓库的教程了……请问是在ssh里面

**Comment by gdy666** [comment]
要想重启也能使用的话那得设置开机启动呀,如果不会设置开机启动的话直接使用一键安装脚本的指令安装一遍就可以了.
看这里
https://github.com/gdy666/lucky-files

**Comment by yishion819** [comment]
> 要想重启也能使用的话那得设置开机启动呀,如果不会设置开机启动的话直接使用一键安装脚本的指令安装一遍就可以了.
> 
> 看这里
> 
> https://github.com/gdy666/lucky-files

我就是用的这个一键安装的，但最后那里没操作，重启后就不行了，需要重新在安装一次，在操作那个代码？

**Comment by yishion819** [comment]
我按照你这个链接先安装curl，按照提起安装成功，然后重启又没了……

**Comment by gdy666** [comment]
默认是禁用外网访问后台的,你需要在设置里面打开外网访问.
正则匹配上这个日志不需要理会,是我忘记注释掉这行日志输出了...
这是你用了从网卡获取Ip和使用了正则才会出现这个日志,后续版本会注释掉这个的.

**Comment by yishion819** [comment]
> 默认是禁用外网访问后台的,你需要在设置里面打开外网访问.
> 
> 正则匹配上这个日志不需要理会,是我忘记注释掉这行日志输出了...
> 
> 这是你用了从网卡获取Ip和使用了正则才会出现这个日志,后续版本会注释掉这个的.

是不是用了你这个插件后，op自带的防火墙就不需要再设置了？

**Comment by gdy666** [comment]
自己看情况吧,一般打开相应端口就可以了不需要再在op的防火墙设置端口转发. 我主路由的ipv6防火墙貌似是直接停用的...

**Comment by yishion819** [comment]
> 自己看情况吧,一般打开相应端口就可以了不需要再在op的防火墙设置端口转发. 我主路由的ipv6防火墙貌似是直接停用的...

好的，谢谢大佬，我是从恩山来的，我看你回贴说了你的qq号，但我这边设置后，移动/联通/电信的4G信号还是无法远程连接，不知道是哪里的问题，如果大佬同意，我就加你qq，麻烦大佬抽空帮我远程看下，如果大佬没空的话，就算了，我再研究下是哪里的问题，打扰了

**Comment by gdy666** [comment]
我猜是防火墙设置问题,如果是光猫拨号参考一下这个.
https://www.kawayii.com/2.html#OpenWRT%E6%93%8D%E4%BD%9C%E8%BF%87%E7%A8%8B
op拨号的话自己上恩山之类的找找如何关闭ipv6防火墙或者打开特定端口吧...

**Comment by yishion819** [comment]
> 我猜是防火墙设置问题,如果是光猫拨号参考一下这个.
> 
> https://www.kawayii.com/2.html#OpenWRT%E6%93%8D%E4%BD%9C%E8%BF%87%E7%A8%8B
> 
> op拨号的话自己上恩山之类的找找如何关闭ipv6防火墙或者打开特定端口吧...

我是路由器拨号，不想关闭ipv6的防火墙，我开始以为op的80端口有问题，我修改成8080的，然后在这个插件的后台管理界面添加了转发规则，结果还是不行……

**Comment by yishion819** [comment]
Callback 调用接口[https://dynv6.com/api/update?hostname=#{yishion819.v6.rocks}&token=G4U7t87PL5zToGzFhLgTcZwdjBs6U1&ipv6=#{240e:0333:0504:4e3a:55d4:b9cb:6357:5d21}]出错：gout.Response() error:Get "https://dynv6.com/api/update?hostname=#%7Byishion819.v6.rocks%7D&token=G4U7t87PL5zToGzFhLgTcZwdjBs6U1&ipv6=%23%7B240e:0333:0504:4e3a:55d4:b9cb:6357:5d21%7D": dial tcp: lookup dynv6.com on [::1]:53: server misbehaving
请问插件里面的日志提示这个是什么意思？麻烦大佬看看

**Comment by gdy666** [comment]
貌似是你运行环境的dns有问题,换个dns或者重启机子试试?

**Comment by yishion819** [comment]
> 貌似是你运行环境的dns有问题,换个dns或者重启机子试试?

好的，谢谢

**Comment by yishion819** [comment]
> 貌似是你运行环境的dns有问题,换个dns或者重启机子试试?
不是dns的问题，换过了，手动重启wan口的时候，有时候正常，有时候不正常，但运营商切ip的时候就不会正常

**Comment by gdy666** [comment]
IP变化的时候或者偶尔出现更新失败一两次很正常吧,除非是经常性很频繁出现更新失败...如果只是偶尔出现你就把动态域名设置里面的时间间隔的值设置少一些,比如60秒.
![QQ截图20220918203635](https://user-images.githubusercontent.com/2849711/190902633-fd398480-c024-4f87-ab78-f1f3bafb747b.png)

**Comment by yishion819** [comment]
> IP变化的时候或者偶尔出现更新失败一两次很正常吧,除非是经常性很频繁出现更新失败...如果只是偶尔出现你就把动态域名设置里面的时间间隔的值设置少一些,比如60秒.
> 
> ![QQ截图20220918203635](https://user-images.githubusercontent.com/2849711/190902633-fd398480-c024-4f87-ab78-f1f3bafb747b.png)
> 
> 

好的，我再试试
